[Telemetry] Add UpdateProjectEventMetadata to ProjectExtension
mono/monodevelop pull request #5347
Opened 2018-07-10 02:31 UTC by bratsche

This adds a way to fetch platform-specific metadata for extra `XS.Solution.Perf.ProjectBuild.*` properties.

This is part of VSTS #598635

2018-07-10 07:54 UTC, iainx approved these changes

2018-07-10 08:11 UTC, mrward approved these changes
Should we have a OnGetProjectEventMetadata method added to the SolutionItemExtension? The default behaviour would be to call SolutionItem.OnGetProjectEventMetadata. That seems to match the current pattern used in the SolutionItemExtension.

2018-07-10 08:12 UTC, mrward requested changes
Meant to comment not approve it.

2018-07-10 11:03 UTC, slluis requested changes
I agree with Matt.

2018-07-10 18:34 UTC, mrward commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectExtension.cs
>  	}
Not sure what this new line is for :)

2018-07-10 18:34 UTC, mrward commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs
> +			return itemExtension.OnGetProjectEventMetadata (metadata, configurationSelector);
I was thinking more along the lines of the SolutionItemExtension.OnProjectEventMetadata method calling into SolutionItem which would create the ProjectEventMetadata. So CreateProjectEventMetadata would be just:
```
public ProjectEventMetadata CreateProjectEventMetadata (ConfigurationSelector configurationSelector)
{
	return ItemExtension.OnGetProjectEventMetadata (configurationSelector);
}
```

Then the SolutionItemExtension would at the end call back into a non-public method on the SolutionItem which would do the creation:

```
internal ProjectEventMetadata OnGetProjectEventMetadata (ConfigurationSelector configurationSelector)
{
	string id = null;
	if (configurationSelector != null) {
		var slnConfig = configurationSelector as SolutionConfigurationSelector;
		if (slnConfig != null) {
			id = slnConfig.Id;
		}
	}

	return new ProjectEventMetadata (id);
}
```

The SolutionItem's GetReferencedItems method has a similar pattern to this.

2018-07-10 18:39 UTC, mrward commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs
> +			return itemExtension.OnGetProjectEventMetadata (metadata, configurationSelector);
Also the protected OnGetProjectEventMetadata (ProjectEventMetadata metadata) should be called at some point here in the OnGetProjectEventMetadata method.

2018-07-11 15:16 UTC, bratsche commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs
> +			return itemExtension.OnGetProjectEventMetadata (metadata, configurationSelector);
@mrward I'm still struggling to get this to work again with these changes. And I don't really understand that `protected OnGetProjectEventMetadata (ProjectEventMetadata metadata)` call there before it returns. Is that what I should be overriding to add the platform-specific metadata? I don't see anywhere to override it from. As far as I understand the places we can override in the addins are deriving from the extensions, not from project/solutionitem.

2018-07-11 15:38 UTC, bratsche commented
@mrward I think this is pretty close to what you suggested now.

2018-07-11 15:44 UTC, mrward commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs
> +		protected virtual ProjectEventMetadata OnGetProjectEventMetadata (ConfigurationSelector configurationSelector, ProjectEventMetadata origMetadata)
So I was more thinking the creation of the project event metadata would be done on the SolutionItem's OnGetProjectEventMetadata. Currently it is being passed in and returned.

The other SolutionItemExtension methods take something as a parameter and then return something else.

`internal protected virtual DateTime OnGetLastBuildTime (ConfigurationSelector configuration)`

2018-07-11 17:45 UTC, mrward commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs
> +				return new ProjectEventMetadata (metadata);
This can just return Item.OnGetProjectEventMetadata. No need to create the ProjectEventMetadata again here.

2018-07-11 17:45 UTC, mrward commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItemExtension.cs
> +			return new ProjectEventMetadata (metadata);
Similar here - no need to create a new ProjectEventMetadata class just return it from the next.OnGetProjectEventMetadata call.

2018-07-11 17:48 UTC, mrward commented
OnEndLoad seems to still be calling the obsolete GetProjectEventMetadata. It is not part of your change but I am not sure that is correct. Shouldn't it be calling the new CreateProjectEventMetadata?

2018-07-11 17:52 UTC, bratsche commented
@iainx ^ Is that intended to still be calling the obsolete `GetProjectEventMetadata()` from `OnEndLoad()` still?

2018-07-11 17:53 UTC, mrward commented
Another thing I am wondering about, which is not part of your change, is how the deprecated methods work. If I am using the old deprecated methods, either overriding one or calling the public one, would we expect the information captured using the new methods to be available here and vice versa?

It is probably not a problem for us since we would just make sure the non-obsolete methods are called. Just wondering. @iainx

2018-07-11 18:02 UTC, iainx commented
I think it should be calling both, calling the new one first and if that returns null calling the obsolete one. It's awkward because we can't stop calling the old obsolete one because it's a API break.

2018-07-11 18:05 UTC, bratsche commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItemExtension.cs
> +			return new ProjectEventMetadata (metadata);
If we don't do this then they don't ever get combined though, right? The whole point of all this was to combine the platform-specific properties into the project properties.

2018-07-11 18:17 UTC, bratsche commented
It used to pass the `ProjectEventMetadata` down the chain and in the extension it would do something like `new IPhoneProjectEventMetadata (metadata)`, but now I don't think it's combining the metadata anymore since I changed `OnGetProjectEventMetadata()` to just take a `ConfigurationSelector` parameter.

2018-07-11 18:19 UTC, mrward reviewed
This is looking good now with the extension and project bits.

Not sure if we want to address the other problems here or not.

2018-07-11 18:22 UTC, mrward commented
In your project extension, such as the IPhone one, you need to call the base class method to get the metadata, then add the new metadata. That is what is missing on that side. You can still do `new IPhoneProjectEventMetadata (metadata)` just call the base class method to get the metadata.

2018-07-11 18:38 UTC, bratsche commented
@mrward Thanks!

2018-07-11 19:31 UTC, bratsche commented
@mrward I think I'd rather have other issues handled in a separate PR, if that's okay with you and @iainx, so I can just get the platform-specific stuff done.

2018-07-12 10:06 UTC, mrward commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs
> +		public ProjectEventMetadata (CounterMetadata metadata, string configurationId)
This constructor does not seem to be used anywhere so I think it can be removed.

2018-07-12 14:03 UTC, mrward approved these changes

2018-07-12 14:42 UTC, slluis approved these changes
Nice!

2018-07-17 15:11 UTC, merged

2018-07-19 16:47 UTC, bratsche commented
@monojenkins backport release-7.6

2018-07-19 16:48 UTC, monojenkins commented
@bratsche backporting to release-7.6 failed, the patch results in conflicts:

```
Applying: [Telemetry] Add UpdateProjectEventMetadata to ProjectExtension
Using index info to reconstruct a base tree...
M	main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
M	main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectExtension.cs
Falling back to patching base and 3-way merge...
Auto-merging main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectExtension.cs
Auto-merging main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
CONFLICT (content): Merge conflict in main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
error: Failed to merge in the changes.
Patch failed at 0001 [Telemetry] Add UpdateProjectEventMetadata to ProjectExtension
```

Please backport manually!