Fixes issue #4377 WebReference addin slows down folder building
mono/monodevelop pull request #5366
Opened 2018-07-11 08:38 UTC by mkrueger

2018-07-11 09:56 UTC, Therzok commented
This works for me, but the proper solution would be to use a bound ItemCollection to the main item collection, like here:
http://source.monodevelop.com/#MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs,88 http://source.monodevelop.com/#MonoDevelop.AddinMaker/AddinProjectFlavor.cs,32

But that means having WebReferenceItem deriving from ProjectItem?

2018-07-11 10:41 UTC, slluis requested changes

2018-07-11 10:41 UTC, slluis commented on main/src/addins/MonoDevelop.WebReferences/MonoDevelop.WebReferences/WebReferencesProjectExtension.cs
> +			Project.ProjectItemRemoved += ItemChanged;
Instead of subscribing the ProjectItemAdded/ProjectItemRemoved events, you can just override OnItemsAdded and OnItemsRemoved, which are defined by ProjectExtension.

2018-07-11 11:53 UTC, Therzok commented
So, my initial proposed solution in the github issue wanted to make use of:
http://source.monodevelop.com/#MonoDevelop.WebReferences/MonoDevelop.WebReferences.WS/WebServiceEngineWS.cs,59
http://source.monodevelop.com/#MonoDevelop.WebReferences/MonoDevelop.WebReferences.WCF/WebServiceEngineWCF.cs,89

Using these to ProjectItem kinds and using `Bind<>` to create the collections.

2018-07-11 12:29 UTC, mkrueger commented
Would require some larger structural changes, updating etc. I just made a minimal cache to fix that issue. But you're right that this approach is probably cleaner. 

But I think my patch is less code needed than getting the Bind way working. It would need some restructuring and a project extension as well - or at least refactoring the WebServiceEnigne to be one.

2018-07-11 13:50 UTC, slluis commented on main/src/addins/MonoDevelop.WebReferences/MonoDevelop.WebReferences/WebReferencesProjectExtension.cs
> +				webReferenceItemsWS = WebReferencesService.WcfEngine.GetReferenceItems (Project).ToList ();
Should be WebReferencesService.WsEngine

2018-07-11 13:53 UTC, slluis commented
I tend to agree with Mike. The PR fixes the problem, we don't need to expend much time refactoring all that code right now.

2018-07-11 19:50 UTC, Therzok approved these changes

2018-07-12 05:39 UTC, mkrueger commented
Cut&Paste == evil - ty :)

2018-07-12 07:22 UTC, slluis approved these changes

2018-07-12 10:57 UTC, merged

2018-07-12 11:03 UTC, Therzok commented
@monojenkins backport release-7.6