Fixing bug with copying build configuration
mono/monodevelop pull request #5834
Opened 2018-09-02 18:09 UTC by Jammer77

If project have:
 
 *<PropertyGroup>*
    *<PreBuildEvent></PreBuildEvent>*
  *</PropertyGroup>*

MonoDevelop adding new build config after it and this project can't build any more. 
My fix changes this situation, and adding new configuration in the right way.

2018-09-03 07:06 UTC, slluis commented
The order of the property groups should not matter in this case. I tried adding that property group to a project and then adding a configuration and the project built fine for me. Which error are you getting?

2018-09-03 07:48 UTC, Jammer77 commented
This is error i've  gotten.  I'm not just copying  configuration. I doing it in the project with preBuild  action.

> Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5,5): Error: The OutputPath property is not set for project 'ColorPicker.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='DebugMac'  Platform='AnyCPU'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform. (ColorPicker)

2018-09-03 07:51 UTC, Jammer77 commented
For my solution i fixed it manually, but i investigated behavior of VSforWindows  and it write copied configuration right after configurations, but not after preBuild actions in the end of the xml.

2018-09-03 07:53 UTC, Jammer77 commented
<img width="1543" alt="image" src="https://user-images.githubusercontent.com/26893798/44974198-9587d700-af67-11e8-9918-b45fe68ea7c3.png">

2018-09-03 07:55 UTC, Jammer77 commented
<img width="1581" alt="image" src="https://user-images.githubusercontent.com/26893798/44974289-dbdd3600-af67-11e8-8b37-6e0cfab1993f.png">

2018-09-03 08:10 UTC, mrward commented
1. Can you post the entire contents of the project file (.csproj)?
2. Does VS on Windows work with the Pre/PostBuildEvents at the start where VS Mac adds them?

2018-09-03 08:27 UTC, Jammer77 commented
[ColorPicker.csproj.zip](https://github.com/mono/monodevelop/files/2344756/ColorPicker.csproj.zip)

2018-09-03 09:03 UTC, Therzok commented
Can we have a failing unit test that passes after this fix is applied?

2018-09-03 09:03 UTC, Therzok submitted a review, later dismissed
Needs tests

2018-09-03 09:50 UTC, Jammer77 commented
Sorry, I have no time for test writing. If it's need it can implement somebody from the teem.

2018-09-03 10:12 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs
> +                    var last = ChildNodes.FindLastIndex(g => g is MSBuildPropertyGroup &&
This is a huge perf hit, as we will look up every property in every property group now.

2018-09-03 11:36 UTC, Jammer77 commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs
> +                    var last = ChildNodes.FindLastIndex(g => g is MSBuildPropertyGroup &&
Sure. 2-4 group property with 8-10 items inside, and we call this method only we have a new one configuration.

2018-09-03 14:07 UTC, Jammer77 commented
So. Can i merge this issue? This is big pain. If you add new configure in the solution, you have to edit all projects manually about 1 day.

2018-09-04 11:31 UTC, slluis requested changes
This can't be merged as is. The ordering of the property groups shouldn't matter in this case. We need a better diagnostic of the problem.

2018-09-12 12:17 UTC, closed without merging