[Core] Reduce number of file watchers used with .NET Core projects  …
mono/monodevelop pull request #6153
Opened 2018-10-01 16:41 UTC by mrward

A file watcher was being created for each SDK style project. When a
solution contains a lot of SDK style projects (e.g. OrchardCore
contains 126 projects) this can then cause Mono's networking stack
to stop working. NuGet restore, check for updates would fail with
errors similar to:

SecureChannelFailure (Unable to write data to the transport connection:
The socket is not connected.)

Since the FileWatcherService has a maximum number file watchers the
project can use the common file watchers instead of creating its own.
This reduces the number of file watchers. For the OrchardCore solution
this reduces the number of file watchers down from 127 to 1.

There are still other NuGet restore problems with the OrchardCore
solution, but this solves one part.

Fixes VSTS #678422 - Unable to restore packages in OrchardCore app

2018-10-01 17:46 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
> +			foreach (string file in Directory.GetFiles (newDirectory, "*", SearchOption.AllDirectories)) {
`Directory.EnumerateFiles` here, as `GetFiles` is `EnumerateFiles ().ToArray()`

2018-10-01 17:47 UTC, mrward commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
> +			foreach (string file in Directory.GetFiles (newDirectory, "*", SearchOption.AllDirectories)) {
Yeah, forgot about EnumerateFiles 👍

2018-10-01 17:47 UTC, Therzok commented on main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/DotNetCoreFileWatcherTests.cs
> +			await FileWatcherService.Add (solution);
Where is the filewatcher remove for this? We might have tests hang if we don't remove it.

2018-10-01 17:48 UTC, mrward commented on main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/DotNetCoreFileWatcherTests.cs
> +			await FileWatcherService.Add (solution);
Happens when the Solution is disposed. No need for an explicit remove.

2018-10-01 17:49 UTC, Therzok approved these changes
Other than enumeration change, LGTM! 👍

2018-10-04 13:55 UTC, mrward commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
> +			// Use FileWatcherService for file created event since this does not run on the UI thread.
It can hang the IDE if there are lot of files being created. Seen this problem when doing an npm install with the project open in the IDE.

2018-10-04 14:43 UTC, slluis commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
> +			// Use FileWatcherService for file created event since this does not run on the UI thread.
If we need to be able to handle file change events in the same thread that originated the event, let's add that capability to FileService. Having file change events in two classes is confusing.

2018-10-15 13:40 UTC, slluis requested changes

2018-10-15 13:40 UTC, slluis commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
> +		public static AsyncEvents AsyncEvents = new AsyncEvents ();
This should be a property.

2018-10-15 13:40 UTC, slluis commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
> +		internal void NotifyFileCreated (FilePath fileName)
We don't need Notify* methods in this class. The idea is that the NotifyFileCreated method in FileService fires the FileService.AsyncEvents.FileCreated event from whatever thread is calling NotifyFileCreated, and it fires FileService.FileCreated in the UI thread.


 events defined in AsyncEvents are raised in the thread that notified then.

2018-10-16 07:45 UTC, slluis approved these changes

2018-10-16 07:46 UTC, slluis commented
@monojenkins backport release-7.7

2018-10-16 13:11 UTC, merged