Fixes VSTS Bug 705785: [Feedback] Search result tab has temporary
mono/monodevelop pull request #6366
Opened 2018-10-17 09:28 UTC by mkrueger

files

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/705785

The user is right that search in whole solution shouldn't include
generated files. However it's a slight behavior change to old
versions. If users want to search in generated files for some reason
they should switch to 'search in directory' instead.

2018-10-17 10:16 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/Scope.cs
> +					if (!filterOptions.NameMatches (file.Name) || !File.Exists (file.Name))
```suggestion
					if (!filterOptions.NameMatches (file.Name)
```

GetFileIsText below does File.Exists.

2018-10-17 10:18 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/Scope.cs
> +									  if (!filterOptions.NameMatches (file.Name) || !File.Exists (file.Name))
```suggestion
									  if (!filterOptions.NameMatches (file.Name))
```

2018-10-17 11:14 UTC, slluis commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs
> +			}
Instead of a new combobox option, can you add an "Include code behind files" checkbox? In this way we can offer that option when the scope selection is workspace, solution or project.

2018-10-18 06:14 UTC, mkrueger commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs
> +			}
Thought about that but I think that would clutter the UI more and I suspect that 99% of the ppl don't need that. It's a real power user feature. 

The bigger question is if we really, really need that ?!? I added it just in case.

2018-10-18 12:12 UTC, slluis commented
I'm re-thinking this fix. In the past we used to get the files from the project files collection and we changed it to GetSourceFilesAsync() to fix the bug https://bugzilla.xamarin.com/show_bug.cgi?id=35343. So using GetSourceFilesAsync() is not about searching on code behind files, it is about finding files imported by msbuild. So it is legit to always call GetSourceFilesAsync() to get the files. What we can do is just skip files in the obj directory.

2018-10-18 14:35 UTC, Therzok commented
Doesn't `Files` contain files from imports?

2018-10-18 18:48 UTC, slluis commented
No, Files only contains what is specified in the csproj.

2018-10-28 15:29 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs
> +				includeCodeBehind.Value = includeCodeBehindItem.Active;
ref cycle here.

2018-10-28 15:30 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs
> +				regexSearch.Value = regexSearchItem.Active;
Ref cycle here.

2018-10-28 15:30 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs
> +				caseSensitive.Value = caseSensitiveItem.Active;
Ref cycle here.

2018-10-28 15:31 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs
> +				recentItem.Activated += delegate (object mySender, EventArgs myE) {
ref cycle here.

2018-10-28 15:31 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs
> +				recentItem.Activated += delegate (object mySender, EventArgs myE) {
Lambda is assigned to `recentItems` event handler, which is ref'd from `this.searchEntry.Menu`, and lambda is a closure capturing `this`

2018-11-06 14:16 UTC, mkrueger commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs
> +		static ConfigurationProperty<bool> caseSensitive = ConfigurationProperty.Create ("CaseSensitive", false);
Doesn't matter much since the dialog got redesigned.

2018-11-06 14:17 UTC, mkrueger commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs
> +				includeCodeBehind.Value = includeCodeBehindItem.Active;
and where is the problem ? We're talking about UI code here.

2018-11-09 16:10 UTC, mkrueger commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs
> +				includeCodeBehind.Value = includeCodeBehindItem.Active;
The GC should be able to throw away cycles if there is no reference to the cycle.

 I'll try it out :). If that's really the case and this can't be handled we should switch the GC :)

2018-11-09 16:33 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs
> +				includeCodeBehind.Value = includeCodeBehindItem.Active;
Gtk# doesn't have weak event handling. It's not a GC problem.

2018-11-15 11:49 UTC, mkrueger commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs
> +				includeCodeBehind.Value = includeCodeBehindItem.Active;
I checked that the finalizer gets called - 

`class CheckMenuItem2 : CheckMenuItem
		{
			string label;
			public CheckMenuItem2 (string label) : base(label)
			{
				this.label = label;
			}
			~CheckMenuItem2 ()
			{
				Console.WriteLine ("finalized !!!" + label);
			}
		}`

2018-11-15 11:53 UTC, mkrueger commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs
> +				recentItem.Activated += delegate (object mySender, EventArgs myE) {
Same as above -

Using 
```
class MenuItem2 : MenuItem
		{
			public MenuItem2 (string label) : base (label)
			{
			}

			~MenuItem2 ()
			{
				Console.WriteLine ("disposed!!!!");
			}
		}
```

Shows that finalizers get called.

2018-11-15 13:54 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs
> +				includeCodeBehind.Value = includeCodeBehindItem.Active;
The event handlers are not on the actual widget, but on the toggleref which holds the object. The managed object can go away, but not the toggleref.

2018-11-16 11:51 UTC, Therzok approved these changes

2018-11-16 14:54 UTC, slluis requested changes
This PR derivated into a UI revamp that is out of scope of this bug, and which should be reviewed by the UX board. All we need to do is ignore files that are under the intermediate folder of a project, and I don't believe anymore that we need a new option for that.

2018-11-26 17:30 UTC, mkrueger commented
So that means the 1st implementation was correct ? 

But anyways let's review it by the UX board. It's improving the dialog a lot IMO.

2018-11-27 06:29 UTC, mkrueger commented
We should review it - it's enhancing the dialog.

2019-05-07 04:46 UTC, closed without merging

2019-05-07 04:47 UTC, mkrueger commented
https://github.com/mono/monodevelop/pull/7458