[NuGet] Support conditional PackageReferences when multi-targeting
mono/monodevelop pull request #6632
Opened 2018-11-20 11:31 UTC by mrward

Use the GenerateRestoreGraphFile MSBuild target to deterine the
package spec information instead of determining this from the project
model. This allows multi-targeting projects and conditional
PackageReferences to be supported.

Fixes VSTS #583482 - PackageReference does not respect condition
Fixes VSTS #572320 - Support conditional NuGet PackageReferences in
multi-targeting projects
Fixes VSTS #572329 - Show per-framework dependencies when multi-targeting
Fixes VSTS #563083 - Using Paket with new .fsproj format

 * Needs more testing and performance checks. Performance problems when restoring a single project that has a large set of project references (e.g. OrchardCore).

2018-11-20 14:31 UTC, Therzok commented on main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/MSBuildPackageSpecCreator.cs
> +			if (File.Exists (resultsPath) && new FileInfo (resultsPath).Length != 0) {
We should use the same file info:
```suggestion
			var fileInfo = new FileInfo (resultsPath);
			if (fileInfo.Exists && fileInfo.Length != 0) {
```

2018-11-20 14:32 UTC, Therzok commented on main/src/addins/MonoDevelop.PackageManagement/NuGet.Commands/MSBuildUtility.cs
> +						monitor.Log,
Shouldn't this be ErrorLog?

2018-11-20 14:32 UTC, Therzok commented on main/src/addins/MonoDevelop.PackageManagement/NuGet.Commands/MSBuildUtility.cs
> +						monitor.Log,
```suggestion
						monitor.ErrorLog,
```

2018-11-20 14:36 UTC, Therzok commented on main/src/addins/MonoDevelop.PackageManagement/NuGet.ProjectManagement/TempFile.cs
> +				if (!File.Exists (filePath)) {
We retry 3 times if the file exists?

2018-11-20 14:37 UTC, mrward commented on main/src/addins/MonoDevelop.PackageManagement/NuGet.Commands/MSBuildUtility.cs
> +						monitor.Log,
I think I did this after looking at [existing code](https://github.com/mono/monodevelop/blob/0a95558a7da163a86a6887b0dfbe78292b4f4283/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/CustomCommand.cs#L301) which also does not use the ErrorLog.

2018-11-20 14:45 UTC, Therzok commented on main/src/addins/MonoDevelop.PackageManagement/NuGet.Commands/MSBuildUtility.cs
> +						monitor.Log,
That code should also be changed.

2018-11-20 18:42 UTC, Therzok approved these changes

2018-12-04 09:52 UTC, mrward commented
Reworked this pull request with some performance improvements. Also fixes a problem with the type system using out of date reference information on project reload.

2018-12-04 10:18 UTC, Therzok approved these changes

2018-12-04 14:29 UTC, slluis requested changes
Two general comments:
1) There are several references to `IdeApp.Workspace.ActiveConfiguration`. The changes you are doing are on the project system, and the project system should not depend on the IDE status. If the configuration is required for getting package information, it should be provided as an argument.
2) There is logic in MSBuildUtility for running msbuild, which involves locating the right mono, msbuild, building the command line, etc. I'd like this logic to be encapsulated in MonoDevelop.Projects.MSBuild, since MSBuildProjectService uses a similar logic.

2018-12-04 18:40 UTC, mrward commented
Moved part of the code out of MSBuildUtility into a new MSBuildProcessService class in the MonoDevelop.Projects.MSBuild project.

Not sure what to do about the IdeApp.Workspace?.ActiveConfiguration. This is used in the NuGet addin, not directly in the project system, and would be based on the current setting in the IDE. I could push this up to higher in the stack if that would be better.

2018-12-05 10:34 UTC, slluis commented
If the code above that uses IdeApp.Workspace ends being called directly or indirectly by the project system, then the configuration must be a parameter that has to be provided by the project system. The case I mean is for example, a project model extension invoking that code to find referenced assemblies or something like that. The project system has no concept of active configuration. An invocation to a method is supposed to always have the same effect, no matter what is the configuration selected in the IDE.

If the above code is only invoked by the NuGet service, then maybe the reference may stay. However, you have to be aware (and users of the api must be aware) that the result of the functions may change depending on what the user selects in the IDE, and the service should probably react to active configuration changes.

2018-12-05 10:57 UTC, mrward commented
When you restore or install a new NuGet packages the current configuration would be used at that time - it is not captured forever. So in the unusual case where the user has package references that are conditional on the platform/configuration they would need to restore the packages to fix the references. I can test this in VS on Windows - I suspect they do not automatically restore on switching configuration.

2018-12-05 11:21 UTC, mrward commented
VS 2017 runs a restore for a .NET Core project when the configuration is switched between Debug/Release even if there are no conditions for the PackageReferences. VS Mac can do the same.

2018-12-10 09:51 UTC, slluis commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/RemoteBuildEngine.cs
> +			OnShuttingDownProjectBuilder (remoteBuilder);
I don't quite understand this commit. If a builder is being shut down it doesn't qualify for being reused for running another target. I don't see in which case the builder could still be in use when UnloadProject is called.

2018-12-10 10:02 UTC, mrward commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/RemoteBuildEngine.cs
> +			OnShuttingDownProjectBuilder (remoteBuilder);
Correct - if UnloadProject is called then the project builder will not be available. The problem is that if there is reference held for the project builder, so it is still in use, then UnloadProject will not be called until the project builder has finished running the target. So a project builder can have its Shutdown method called but UnloadProject will not be called since it is still running. This can result in the project builder being re-used in [GetRemoteProjectBuilder](https://github.com/mono/monodevelop/blob/b7f59d3c01662a66cae069e6dca66ad9e34cb7d4/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/RemoteBuildEngine.cs#L117) since it is still in the list even though it has been marked as shutting down.

 I added a unit test which reproduced this problem before fixing the bug.

2018-12-10 12:00 UTC, slluis commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/RemoteBuildEngine.cs
> +			OnShuttingDownProjectBuilder (remoteBuilder);
I think the real problem is that `GetRemoteProjectBuilder()` doesn't take into account that `RemoteProjectBuilder.AddReference()` will fail if the builder is being shut down. The fix would be for `GetRemoteProjectBuilder()` to check the result of `AddReference` before returning a builder, and if it fails, unlist the builder and create a new one.

2018-12-10 18:43 UTC, mrward commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/RemoteBuildEngine.cs
> +			OnShuttingDownProjectBuilder (remoteBuilder);
Reworked the code so the AddReference method is checked in GetRemoteProjectBuilder.

2018-12-11 08:50 UTC, slluis commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/RemoteBuildEngine.cs
>  						builder.ContinueWith (t => t.Result.AddReference (), TaskContinuationOptions.NotOnFaulted);
AddReference should also be checked here, since by the time this continuation is executed, the builder may already have been shut down.

2018-12-11 10:40 UTC, slluis approved these changes

2018-12-12 12:22 UTC, merged