Fixes issue #6898 FileWatcherService locks UI Thread on linux. In
mono/monodevelop pull request #6900
Opened 2019-01-15 14:44 UTC by mkrueger

conjunction with the mono patch:
https://github.com/mono/mono/pull/12432

I think the mono patch is the real fix here but I optimized the
UpdateWatchers.

2019-01-15 17:11 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs
> +				if (newWatchers.Count == 0) {
Do we ever hit this case as a fast path?

2019-01-15 17:21 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs
> +				if (newWatchers.Count == 0) {
That would mean that we cleared all the filewatchers, which I don't think will happen often. I would go for simplicity of code here and merge the loop of this and the one below.

`newWatchers.Contains (directory)` in the second loop below will exit early as the collection has no elements.

2019-01-16 07:12 UTC, mkrueger commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs
> +				if (newWatchers.Count == 0) {
It was in the original code :), therefore I decided not to remove it. But y doesn't make much difference here.

2019-01-16 11:48 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs
> +				if (newWatchers.Count == 0) {
We can have up to 8 watchers, due to the algorithm.

2019-01-16 11:49 UTC, Therzok approved these changes

2019-01-16 11:50 UTC, Therzok commented
Okay, I remember why I added the extra list. See test failures:
```
2019-01-16T08:08:27.6125640Z    System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
2019-01-16T08:08:27.6126540Z   at System.Collections.Generic.Dictionary`2+Enumerator[TKey,TValue].MoveNext () [0x00090] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs:1202 
2019-01-16T08:08:27.6126750Z   at MonoDevelop.Projects.FileWatcherService.UpdateWatchers (System.Threading.CancellationToken token) [0x00100] in /Users/vsts/agent/2.144.0/work/1/s/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs:108 
2019-01-16T08:08:27.6126930Z   at MonoDevelop.Projects.FileWatcherService+<>c__DisplayClass8_0.<UpdateWatchersAsync>b__0 () [0x00000] in /Users/vsts/agent/2.144.0/work/1/s/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs:79 
2019-01-16T08:08:27.6127780Z   at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2500 
2019-01-16T08:08:27.6128670Z   at System.Threading.Tasks.Task.Execute () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2343 
2019-01-16T08:08:27.6129340Z --- End of stack trace from previous location where exception was thrown ---
```

Also, it looks like the line endings were changed.

2019-01-18 16:39 UTC, Therzok requested changes

2019-01-18 16:39 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs
> +		static List<FilePath> toRemove = new List<FilePath> ();
toRemove is never cleared

2019-01-18 16:40 UTC, Therzok approved these changes
It is, misread.

2019-01-18 23:52 UTC, merged