Fixes VSTS Bug 715151: [Feedback] 64 bit unit testing is not supported
mono/monodevelop pull request #6911
Opened 2019-01-17 10:13 UTC by mkrueger

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/715151

Unit testing now values the platfom target setting.

2019-01-17 18:29 UTC, Therzok approved these changes

2019-01-17 18:30 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
> +    <InternalsVisibleTo Include="MonoDevelop.UnitTesting.NUnit" />
Don't like IVT here. Can't we expose this API somehow?

2019-01-17 18:30 UTC, Therzok requested changes
Remove IVT

2019-01-18 10:35 UTC, mkrueger commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
> +    <InternalsVisibleTo Include="MonoDevelop.UnitTesting.NUnit" />
No I don't want to make that API public.

2019-01-18 11:23 UTC, mkrueger commented
@Therzok: I don't want to change the public API. We should stop just popping in public helper methods from everywhere just because we need to use them internally.

2019-01-18 12:17 UTC, Therzok approved these changes

2019-01-18 14:16 UTC, slluis approved these changes
Nice!

2019-01-18 17:04 UTC, merged