[VersionControl] Fix problem notifying deleted files (Git)
mono/monodevelop pull request #7149
Opened 2019-02-14 12:25 UTC by jsuarezruiz

After deleting a file, and trying to make Commit the change with the deleted file does not appear.
It can cause problems when trying to commit without detecting the change.

Before:
![delete-fails](https://user-images.githubusercontent.com/6755973/52786462-2dcbd100-305b-11e9-97ee-5be1afe654c9.gif)
Now:
![delete-ok](https://user-images.githubusercontent.com/6755973/52786655-b8143500-305b-11e9-92bb-51b458bd3ad3.gif)

Fixes gh #7119

2019-02-14 12:44 UTC, Therzok commented on main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlService.cs
> +						repo.Update (path, false, monitor);
This will cause a pull for every renamed file.

2019-02-14 13:12 UTC, jsuarezruiz commented on main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlService.cs
> +						repo.Update (path, false, monitor);
Right, I just changed this part.

2019-02-14 13:47 UTC, slluis commented
Shouldn't this be handled through VersionControlFileSystemExtension ?

2019-02-15 08:45 UTC, jsuarezruiz commented
You're right, Lluis. `VersionControlFileSystemExtension` already manages all these events (add, delete files, modify folders, etc). In addition, it invokes `FileStatusChanged`, used by the `StatusView` to refresh the VCS changes. I have added more invocations  of FileStatusChanged in other `FileService` operations such as deleting files, etc.

2019-02-18 14:46 UTC, slluis commented
NotifyFilesChanged is meant to be called when a file is modified, not when it is deleted. Can't the status view just listen to file removed events?

2019-02-18 20:21 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
> +				foreach (var fsFiles in files.GroupBy (f => GetFileSystemForPath (f, false)))
Why?

2019-02-18 20:22 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
> +				foreach (var fsFiles in files.GroupBy (f => GetFileSystemForPath (f, false)))
We shoudl listen to FileService.FileRemoved in the StatusView.

2019-02-19 10:17 UTC, slluis commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
> +				foreach (var fsFiles in files.GroupBy (f => GetFileSystemForPath (f, false)))
Not really, it should listen to status change events from VersionControlService.

2019-02-20 10:48 UTC, Therzok submitted a review, later dismissed

2019-03-07 09:38 UTC, slluis requested changes
I don't think the fix needs to be done in StatusView. StatusView already handles the case of a file that changes its status to Deleted. If you use the Remove command from the version control menu, the StatusView will be correctly updated. 

Physically deleting a file from the solution pad is a just a special case of the above. The file is both removed from version control and deleted from disk. The difference is that in the first case, the Remove command [calls](https://github.com/mono/monodevelop/blob/master/main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/AddRemoveMoveCommand.cs#L135) `VersionControlService.NotifyFileStatusChanged()` to inform that the file has been removed from version control, and StatusView, which is subscribed to that event, updates the list correctly. In the second case, nobody is calling `NotifyFileStatusChanged()`.

So the question is, who should be calling `NotifyFileStatusChanged()` in the second case? We are currently using different approaches for notifying status changes. On one hand, the version control commands (such the Remove command I mentioned) make explicit calls to `NotifyFileStatusChanged()` when operations are completed. On the other hand, repository implementations call that method in different cases (for example GitRepository does it when stashing or switching branches). I think that notifying status changes should be the responsibility of repository implementations, since only repositories know when status really changes, and ensures that notifications will be properly sent no matter who initiated an operation.

And that's is really the source of the bug. The Remove command calls `DeleteFiles()` on the repository, and then calls `NotifyFileStatusChanged()`. When a file is deleted from the solution pad, `DeleteFiles()` ends being called through `VersionControlFileSystemExtension`, but nobody calls `NotifyFileStatusChanged()`. So the fix should be to just make the repository call `NotifyFileStatusChanged()` in `DeleteFiles()`, and that should cover both cases.

When we redesign the version control infrastructure we should make it more explicit that the responsibility of notifying status changes is on the repository.

2019-03-14 10:37 UTC, jsuarezruiz commented
Thanks for the detailed feedback Lluis. I have undone the previous changes by adding your suggestion, calling `NotifyFileStatusChanged()` in `DeleteFiles()` and iworks (ignoring the cache problems cases solved in another PR).

2019-03-14 11:26 UTC, slluis commented on main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlService.cs
> +					NotifyFileStatusChanged (new FileUpdateEventArgs (repo, path, file.ProjectFile.Subtype == Subtype.Directory));
This shouldn't be necessary, since it will be invoked by Repository.DeleteFiles

2019-03-14 11:27 UTC, slluis commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
> +					fsFiles.Key.NotifyFilesDeleted (fsFiles);
This shouldn't be necessary.

2019-03-15 11:14 UTC, jsuarezruiz commented
To simplify the review and the historical, we will unify this PR with https://github.com/mono/monodevelop/pull/7314 in a new one.

2019-03-15 11:14 UTC, closed without merging

2019-03-15 12:33 UTC, jsuarezruiz commented
New related PR: https://github.com/mono/monodevelop/pull/7345