[IDE] Track whether a file load was initiated by the File Manager better
mono/monodevelop pull request #7320
Opened 2019-03-07 17:00 UTC by iainx

Instead of using a timer that isn't very accurate, track whether or not a
file load was initiated by the FileManager by passing a boolean to the events

Fixes VSTS #806672 https://devdiv.visualstudio.com/DevDiv/_workitems/edit/806672

2019-03-07 17:00 UTC, iainx commented
@monojenkins backport release-8.0

2019-03-07 17:09 UTC, mrward reviewed
Should we make all use of InitiatedByFileManager internal? Do we want/need this to be public?

2019-03-07 17:10 UTC, iainx commented
We don't, no.

2019-03-07 17:11 UTC, iainx commented
But there were a few places that we couldn't make it internal due to internal not being visible IIRC

2019-03-11 13:22 UTC, iainx commented
@slluis Updated to take your idea into consideration

2019-03-11 14:42 UTC, Therzok commented on main/src/addins/MacPlatform/MacPlatform.cs
> +					MonoDevelop.Core.Runtime.RunInMainThread ( () => {
Runtime.RunInMainThread is sync if we're already on the main thread.

2019-03-11 14:42 UTC, Therzok commented on main/src/addins/MacPlatform/MacPlatform.cs
> +					MonoDevelop.Core.Runtime.RunInMainThread ( () => {
So this changes behaviour.

2019-03-11 14:44 UTC, Therzok commented on main/src/addins/MacPlatform/MacPlatform.cs
> +						).ContinueWith ((result) => {
I keep forgetting the basic TPL APIs, does this continue on the same scheduler (main thread) or thread pool?

2019-03-11 14:44 UTC, Therzok commented on main/src/addins/MacPlatform/MacPlatform.cs
> +					Core.Runtime.RunInMainThread (() => {
Same here, change of semantics.

2019-03-14 11:03 UTC, slluis requested changes

2019-03-14 11:03 UTC, slluis commented on main/src/addins/MacPlatform/MacPlatform.cs
> +						IdeApp.StartTimeToCodeTimer ();
This is not right, it should be measuring time since startup, not since the open message was received.

2019-03-14 11:03 UTC, slluis commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
> +			LoggingService.LogInfo ("Processing TTC");
All of those LogInfo should be LogDebug

2019-03-14 11:04 UTC, slluis commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
> +			ttcTimeout = GLib.Timeout.Add (ttcDuration, () => {
BTW, I think ttcDuration of 6s is too much

2019-03-14 16:25 UTC, iainx commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
> +			ttcTimeout = GLib.Timeout.Add (ttcDuration, () => {
6s was what was needed for my machine when I tested it. I had 3 seconds initially but it was timing out.

2019-03-14 16:27 UTC, iainx commented on main/src/addins/MacPlatform/MacPlatform.cs
> +						IdeApp.StartTimeToCodeTimer ();
It's in theory corrected at the end.

But if we using a timer since startup, and don't receive an open event, then the timer will never be stopped, unless we use yet another timer to track whether we got the open event

2019-03-14 16:54 UTC, slluis commented on main/src/addins/MacPlatform/MacPlatform.cs
> +						IdeApp.StartTimeToCodeTimer ();
Well, a Stopwatch is not a real timer, it just stores a timestamp, it doesn't matter if we don't stop it.

2019-03-14 16:57 UTC, slluis commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
> +			ttcTimeout = GLib.Timeout.Add (ttcDuration, () => {
6 seconds between Start Window showing up and getting the open document event? that's a lot. For me there isn't even time to render the Start Window.

2019-03-15 18:13 UTC, slluis commented on main/src/addins/MacPlatform/MacPlatform.cs
> +				return TimeToCodeMetadata.DocumentType.File;
No no, IsWorkspaceItemFile() will return true for any WorkspaceItem subclass (such as a Solution). IsSolutionItemFile() will return true for any SolutionItem subclass (such as a Project). In both cases it should return a TimeToCodeMetadata.DocumentType.Solution.

2019-03-18 10:41 UTC, slluis approved these changes

2019-03-18 10:42 UTC, merged

2019-03-18 10:46 UTC, slluis commented
@monojenkins backport release-8.0-integration