[Core] Fix MSBuildEngineManager disposed error
mono/monodevelop pull request #7332
Opened 2019-03-11 15:36 UTC by mrward

Dispose the MSBuildEngineManager after the project active tasks have
completed. This should avoid the MSBuildEngineManager being used
by the project after it has been disposed.

```
  System.ObjectDisposedException: Cannot access a disposed object.
  Object name: 'MSBuildEngineManager'.
    at MonoDevelop.Projects.MSBuild.MSBuildEngineManager.GetEngine (System.Boolean supportsMSBuild) [0x0001e] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEngineManager.cs:55
    at MonoDevelop.Projects.MSBuild.MSBuildProject.LoadNativeInstance (System.Boolean evaluateItems) [0x0005b] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs:498
    at MonoDevelop.Projects.MSBuild.MSBuildProjectInstance.Evaluate () [0x00019] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectInstance.cs:92
    at MonoDevelop.Projects.ProjectRunConfiguration.Initialize (MonoDevelop.Projects.Project project) [0x00038] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectRunConfiguration.cs:52
    at MonoDevelop.Projects.AssemblyRunConfiguration.Initialize (MonoDevelop.Projects.Project project) [0x00001] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/AssemblyRunConfiguration.cs:49
    at MonoDevelop.DotNetCore.DotNetCoreRunConfiguration.Initialize (MonoDevelop.Projects.Project project) [0x00019] in monodevelop/main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreRunConfiguration.cs:87
    at MonoDevelop.Projects.Project.CreateRunConfigurationInternal (System.String name) [0x00009] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs:343
    at MonoDevelop.Projects.Project.WriteRunConfigurations (MonoDevelop.Core.ProgressMonitor monitor, MonoDevelop.Projects.MSBuild.MSBuildProject msproject, MonoDevelop.Projects.MSBuild.IMSBuildPropertySet globalGroup) [0x00043] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs:3444
    at MonoDevelop.Projects.Project.OnWriteProject (MonoDevelop.Core.ProgressMonitor monitor, MonoDevelop.Projects.MSBuild.MSBuildProject msproject) [0x00045] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs:3299
    at MonoDevelop.Projects.DotNetProject.OnWriteProject (MonoDevelop.Core.ProgressMonitor monitor, MonoDevelop.Projects.MSBuild.MSBuildProject msproject) [0x00001] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs:2037
```

Fixes VSTS #797958 - MSBuildEngineManager disposed error

2019-03-11 15:43 UTC, Therzok commented
My take on this is that APIs don't properly pass the cancellationtoken that is in BindTask, thus they're not cancelled on dispose.

Although, if the implementation does not take cancellation into account, it'll still NRE.

So on that front, looks good to me!

2019-03-11 15:58 UTC, mrward commented
Not using the BindTask cancellation token is another problem which needs looking at. I tried making that change, based on your comment a while ago, whilst looking at this bug for the GetReferenceAssemblies method - however it did not fix the MSBuildEngineManager being used after it is disposed. There seem to be some cases where it could be used whilst the token was disposed.

We also have some null references in the RunMSBuildTarget method if the project is disposed. Random thoughts here:
- Ensure BindTask cancellation token is associated with the progress monitor here.
   - Had several other IDE log errors occur here when the BindTask's token was passed through with GetReferenceAssemblies. Aborting the thread, and some others.
- Check the MSBuildProject is not null before using it. Then if the progress monitor has been cancelled handle that case - maybe by throwing a task canceled operation - or perhaps return no items or a special error TargetEvaluationResult (might be better).

2019-03-11 18:53 UTC, Therzok approved these changes

2019-03-12 08:39 UTC, slluis requested changes
We already delay disposal when there are tasks running: https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/WorkspaceObject.cs#L220. The problem is that this code only takes into account tasks initiated in the object being disposed, but not in child objects. I think a better solution would be to recursively get all the children (there is a GetChildren() method in WorkspaceObject) and then get all the tasks for all the children. Also, if an object hierarchy is being disposed, it should not allow new tasks to be bound to any object in the hierarchy.

2019-03-12 12:52 UTC, mrward commented
Updated after review.

2019-03-12 14:03 UTC, Therzok approved these changes

2019-03-12 14:03 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/WorkspaceObject.cs
> +					return Task.FromCanceled<T> (new CancellationToken (true));
Shouldn't we use disposeCancellation here?

2019-03-12 14:12 UTC, mrward commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/WorkspaceObject.cs
> +					return Task.FromCanceled<T> (new CancellationToken (true));
The disposeCancellation may not be cancelled at this point so I did not want to use it. Calling Solution.Dispose will mark all child items as `disposing` but they may not yet have had their Dispose method called if there are still active tasks. SolutionFolder disposes its child items in its OnDispose method which could be called sometime later on.

I did think about using the disposeCancellation if it was cancelled but just returning a task that is cancelled seemed to be less code.

However this is making me think about the disposing. Seems like SolutionFolder will now wait for all its projects to finish their tasks before Project.Dispose is called. Which may avoid the null MSBuildProject but means tasks are not going to be cancelled as early as they were before.

2019-03-12 14:19 UTC, slluis approved these changes
👍

2019-03-12 14:21 UTC, mrward commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/WorkspaceObject.cs
> +					return Task.FromCanceled<T> (new CancellationToken (true));
Mmm, maybe when we get the active tasks for the child items we should also call `disposeCancellation.Cancel()` for each child item. The child item's Dispose method could be called later on when the tasks have completed. Then we could use the disposeCancellation in the BindTask instead of a separate disposing flag.

2019-03-12 14:26 UTC, slluis commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/WorkspaceObject.cs
> +					return Task.FromCanceled<T> (new CancellationToken (true));
Makes sense

2019-03-12 14:43 UTC, mrward commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/WorkspaceObject.cs
> +					return Task.FromCanceled<T> (new CancellationToken (true));
Updated the code to use the disposeCancellation.

2019-03-12 14:48 UTC, Therzok approved these changes
Looks great!

2019-03-13 10:26 UTC, merged

2019-03-13 10:27 UTC, slluis commented
@monojenkins backport release-8.0-integration