[Ide] Adds feature in MonoDevelop to pin opened tabs
mono/monodevelop pull request #7536
Opened 2019-05-10 02:36 UTC by netonjm

Enables our document bar to pin tabs with some additional options in the contextual menu
It also includes a flag in settings to enable/disable the feature which is in the same panel like windows to parity with VS, and in the future, we can include here the Preview tabs feature.

![dragdrop](https://user-images.githubusercontent.com/1587480/57498598-b2d22980-72dc-11e9-93b9-defbc78b3f42.gif)

This feature allows to lock some of your most used windows (tabs)
to easily detect and open like VS2013 added.

Fixes VSTS #890509 - Add support for pinned tabs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/890509

- Adds Pin/Unpin tab feature clicking right button (contextual menu) in tab or Shortcut key
-Don't call ping events if isPinned value has no change
-Reuses current CloseAllHandler logic and make its more flexible
-Fixes changes to use a ImmutableArray<ViewContent> instead a List
-Adds a new Tab and Windows options panel and usage of ConfigurationProperty
-Removes nested lambda with capture.
-Removes an extra array conversion and makes the code clearer
-Removes extra allocations using Min/MaxValue instead OrderBy

Screenshot from settings:

![image](https://user-images.githubusercontent.com/1587480/53112756-47c85080-3540-11e9-988d-a9fb9c1c5946.png)

Fixes VSTS #890509 - Add support for pinned tabs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/890509

Includes fixes from:
#2487 and #2449 and #2606

2019-05-20 16:23 UTC, netonjm commented
Rebased on the top of master 👍

2019-05-20 18:19 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockNotebook.cs
> +				pages.ToList ().ForEach (d => d.IsPinned = false);
please use foreach here.

2019-05-21 08:55 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockNotebook.cs
> +				pages.ToList ().ForEach (d => d.IsPinned = false);
Fixed

2019-05-22 07:26 UTC, Therzok approved these changes

2019-05-23 14:50 UTC, sevoku commented
LGTM!

But do we really need a setting for this? cc @hbons for wording

Also, let's enable it by default? Or is it off by default on VS on Windows?

2019-05-27 15:05 UTC, sevoku commented
Per discussion with @hbons on Slack, the new preferences panel is not necessary. On Windows it's common to have a checkbox for each and every little thing, but on other platforms (especially Mac) less is more. We don't see any benefit for the user to be able to disable this feature (same applies to preview tabs) and if we introduce this, we should also add properties for many more Shell features (like split view, floating pads, etc.), such fine graned feature toggles don't make much sense.

If the idea behind this panel was to make it possible to disable it in case it doesn't work as expected (like a feature flag for a preview feature), then we should add a special preview property panel, for such kind of things. But I'd rather do some thorough testing and ship it as it is (without the panel).

2019-05-30 14:33 UTC, netonjm commented
Removed the settings panel, enabled by default and rebased 👍  @sevoku @slluis

2019-05-30 17:03 UTC, netonjm commented
Green! 💃

2019-06-26 08:16 UTC, netonjm commented
rebased

2019-06-26 08:35 UTC, Therzok commented
@slluis can we merge this?

2019-06-26 11:15 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/FileTabCommands.cs
> +			var contents = IdeApp.Workbench.Documents.Where (doc => ((SdiWorkspaceWindow)doc.Window).TabControl == activeNotebook && GetTabFromDocument (doc).IsPinned)
Nit:
There's a SelectAsArray extension method [here](http://source.roslyn.io/#Microsoft.CodeAnalysis/Collections/ImmutableArrayExtensions.cs,365be1a01db3ca7a)

2019-06-26 11:15 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/FileTabCommands.cs
> +			return new ImmutableArray<Document> () { active.Window.Document };
`ImmutableArray.Create (active.Window.Document);`

2019-06-26 11:15 UTC, Therzok approved these changes

2019-07-09 08:25 UTC, netonjm commented
rebased

2019-07-11 09:36 UTC, netonjm commented
Failing test is not related

2019-07-11 09:54 UTC, jsuarezruiz commented
I have been doing some tests of this branch. I love the idea!.
 My feedback:
- The icon to pin a tab looks nice on both themes (light and dark).
- Reordering tests are satisfactory. You can reorder pinned tabs between them. You can not mix pinned tabs with not pinned ones.
- The biggest problem I have found, is when reopen a project with pinned tabs. Initially they do not remember the state and appear as not pinned. Trying to pin another tab is when it refreshes the state.

![fixed-tabs-error](https://user-images.githubusercontent.com/6755973/61041443-9a60b700-a3d2-11e9-9135-faabf3980e6f.gif)

2019-07-11 10:02 UTC, netonjm commented
Thanks for the review Javier! Related to store the current pinned tabs yes, I didn't include it because we need to think about where to store that information, I understand that it is related to each project so it may make sense in the userconfiguration, but it needs to be defined. we could open a issue to file it.

2019-07-11 17:12 UTC, jmatthiesen commented
Adding @vancura to comment on the icon usage. Vaclav - would love your thoughts on the icon used for a pin that can be tabbed, versus an already pinned tab.

Untabbed pin, ready to tab:
![image](https://user-images.githubusercontent.com/1333029/61070784-536bc500-a3c4-11e9-9358-ef1ce7902fa5.png)

Tabbed pin:
![image](https://user-images.githubusercontent.com/1333029/61070810-61b9e100-a3c4-11e9-91ac-79e9f1c3e586.png)

2019-07-12 15:45 UTC, netonjm commented
> Adding @vancura to comment on the icon usage. Vaclav - would love your thoughts on the icon used for a pin that can be tabbed, versus an already pinned tab.
> 
> Untabbed pin, ready to tab:
> ![image](https://user-images.githubusercontent.com/1333029/61070784-536bc500-a3c4-11e9-9358-ef1ce7902fa5.png)
> 
> Tabbed pin:
> ![image](https://user-images.githubusercontent.com/1333029/61070810-61b9e100-a3c4-11e9-91ac-79e9f1c3e586.png)

Only for the records https://github.com/mono/monodevelop/pull/2449#issuecomment-303248814

2019-07-29 09:30 UTC, sevoku requested changes
This works really nice! But see my comments, ready to merge once addressed :)

2019-07-29 09:42 UTC, vancura commented
Re icons: do you have the final icons? They're at https://devdiv-design.visualstudio.com/D3%20Studio/_workitems/edit/7382/ (the newer file, Fix.zip).

2019-07-29 10:43 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/FileTabCommands.cs
> +			var contents = IdeApp.Workbench.Documents.Where (doc => ((SdiWorkspaceWindow)doc.Window).TabControl == activeNotebook && GetTabFromDocument (doc).IsPinned)
Fixed

2019-07-29 11:19 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockNotebookTab.cs
> +				if (OnChangedPinned != null)
Fixed

2019-07-29 11:19 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml
> +			shortcut = "Control|Shift|P"
Fixed

2019-07-29 11:19 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml
> +			shortcut = "Control|Alt|P"
Fixed

2019-07-29 13:24 UTC, sevoku approved these changes

2019-07-29 13:28 UTC, sevoku commented
@netonjm are the new icons already included?

2019-07-29 13:33 UTC, sevoku commented
Oh and what about:

> When reopen a project with pinned tabs do not remember the state and appear as not pinned.

Maybe we could simply store the state in UserPrefs.xml?

2019-07-30 08:54 UTC, netonjm commented
Added persistency and new icons 

![lastdocumentopened](https://user-images.githubusercontent.com/1587480/62115209-54ec2700-b2b8-11e9-815d-b02c2cb69b26.gif)

2019-07-30 14:02 UTC, sevoku approved these changes

2019-08-01 17:22 UTC, merged

2019-08-01 18:24 UTC, netonjm commented
👏🏻👏🏻👏🏻👏🏻🍾

2019-08-03 04:17 UTC, Therzok commented
Nicely done!