Launch settings fix
mono/monodevelop pull request #7683
Opened 2019-05-27 14:18 UTC by jtorres

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/862782

Specs https://microsoft-my.sharepoint.com/:w:/p/mhutch/EfsOmr-aDnJMkI1Dv1QQIrcBd-kon2e8qB9QicNVkq3E-A?e=mYbAcu

2019-05-27 16:51 UTC, rodrmoya commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
> +					}
hmm, not sure what this does, it seems to just set to the item that was retrieved in line 219 again, by retrieving its index and setting it by that index??

2019-05-27 16:55 UTC, rodrmoya commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/ILaunchProfile.cs
>  	{
Does this need to be public?

2019-05-27 16:55 UTC, rodrmoya commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/LaunchProfileData.cs
>  	{
Same here, does it need to be public?

2019-05-27 17:00 UTC, jtorres commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/LaunchProfileData.cs
>  	{
yes, `LaunchProfileData` is used by AspnNetCoreConfiguration which is public

2019-05-27 17:00 UTC, jtorres commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/ILaunchProfile.cs
>  	{
same, since LaunchProfileData is public, it should be public

2019-05-27 17:03 UTC, jtorres commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
> +					}
right somehow I missed a step before `this.Project.RunConfigurations [index] = runConfig` that copies `profile` values to `runconfig`... will fix

2019-05-27 17:48 UTC, Therzok commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
> +			foreach (var conf in aspNetCoreRunConfs) {
Maybe also clear/null out the dictionary here.

2019-05-27 17:50 UTC, Therzok commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreRunConfiguration.cs
> +		public void OnSaveRequested () => SaveRequested?.Invoke (this, EventArgs.Empty);
Does this have to be public?

2019-05-27 17:52 UTC, Therzok commented
There's a lot of mixed whitespace here.

2019-05-28 09:16 UTC, mrward commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/LaunchProfileProvider.cs
> +				if (!Profiles.ContainsKey (defaultNamespace)) {
TryGet?

2019-05-28 09:16 UTC, mrward commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
>  		}
I think we should follow the same pattern as for NotifyItemsRemoved.

Project.NotifyItemsRemoved -> ProjectExtension.OnItemsRemoved -> Project.OnItemsRemoved

Also I think it should pass the full set of items instead of the name of each one individually.

We could also implement the same pattern when a run config is added whilst we are added the pattern for removing.

2019-05-28 09:16 UTC, mrward commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
> +				updating = true;
FileService_FileChanged I think runs on the UI thread so we do not need a lock here. A lock would make sense if we were running this on another background thread.

2019-05-28 11:20 UTC, Therzok commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
> +			if (!launchProfileProvider.Profiles.ContainsKey (name)) {
TryGetValue here?

2019-06-13 14:24 UTC, rodrmoya commented
I wonder if we could easily have a high level test, that created a project, then a couple run configs and built on both configs and checking some condition?

2019-06-25 14:06 UTC, rodrmoya approved these changes

2019-07-12 13:44 UTC, mrward reviewed
Everything else looks good to me.

Just two minor questions about public classes and some possible code duplication.

2019-07-12 13:44 UTC, mrward commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
> +				}
This code is almost, but not quite, identical to similar code in OnItemReady - can this code be shared instead of duplicating it here?

2019-07-12 13:44 UTC, mrward commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/ILaunchProfile.cs
>  	{
Asking the same question as Rodrigo here - does this and the LaunchProfileData need to be public. Whilst AspNetCoreConfiguration is public the LaunchProfileData is not public on AspNetCoreConfiguration. It seems like we could make LaunchProfileData and ILaunchProfile non-public.

2019-07-12 14:34 UTC, mrward commented
Adding or removing a profile from launchSettings.json - the main toolbar does not update with this new run configuration. If you add/remove a run config from project options the main toolbar updates.

Adding a new user specific run config adds an entry into the launchSettings.json - not sure what the expected behaviour here. Not sure I understand the mappings here and how things should be synchronised. The spec mentions ignoring user specific run configurations - but not sure if that is just on load or all the time.

2019-07-15 18:52 UTC, jtorres commented
I need to run a smoke test after lasts commits

2019-07-18 19:01 UTC, jtorres commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/ILaunchProfile.cs
>  	{
ok, set LaunchProfileData to internal

2019-07-18 19:27 UTC, Therzok commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
> +			aspNetCoreRunConfs.Clear ();
No need to clear if we set it to null.

2019-07-18 19:28 UTC, Therzok commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
> +				launchProfileProvider.Profiles.TryRemove (item.Name, out var _);
```suggestion
				launchProfileProvider.Profiles.TryRemove (item.Name, out _);
```

2019-07-18 19:29 UTC, Therzok reviewed
LGTM!

2019-07-22 10:44 UTC, slluis requested changes
We need to document test scenarios and use cases.

2019-07-31 16:37 UTC, mrward commented
- Could not test everything since reloading the solution with new run configs throws the null reference exception that Sayed reported.

- Seems to be some problems with shared versus user run configs. From the spec the user specific run configs should be ignored but when you create a user specific run config the launchsettings.json file is updated.

- A shared run configuration does not seem to be created for the Default launchSettings.json profile. From the spec I was assuming that would be the case - maybe that is not the case for Default.

2019-08-03 06:16 UTC, Therzok commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
> +			if (!launchProfileProvider.Profiles.TryGetValue (key, out var _)) {
```suggestion
			if (!launchProfileProvider.Profiles.TryGetValue (key, out profile)) {
```

2019-08-03 06:16 UTC, Therzok commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
> +				profile = launchProfileProvider.Profiles [key];
Since we avoided double lookup, we can remove this block.

2019-08-03 07:06 UTC, Therzok commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/LaunchProfileProvider.cs
> +					var defaultProfile = CreateDefaultProfile ();
```csharp
return Profiles [defaultNamespace] = CreateDefaultProfile ();
```

2019-08-03 07:09 UTC, Therzok commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/LaunchProfileProvider.cs
> +		public ConcurrentDictionary<string, LaunchProfileData> Profiles { get; set; }
Why can we publicly set the Profiles dictionary? Should this be readonly?
```suggestion
		public ConcurrentDictionary<string, LaunchProfileData> Profiles { get; }
```

2019-08-03 07:22 UTC, Therzok commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/LaunchProfileProvider.cs
> +			} catch {
```csharp
try {
        using var fs = File.OpenRead (LaunchSettingsJsonPath);
	using var sr = new StreamReader (fs);
	using var reader = new JsonTextReader (sr);
	return JObject.Load (reader);
} catch (JsonReaderException e) {
	LoggingService.LogInternalError ($"Failed to parse Json {LaunchSettingsJsonPath}", e);
}
```

2019-08-03 07:23 UTC, Therzok commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/LaunchProfileProvider.cs
> +		public LaunchProfileData AddNewProfile (string name)
Should we do validation if the profile already exists?

2019-08-03 07:24 UTC, Therzok commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/LaunchProfileProvider.cs
> +			var newProfile = CreateProfile (name);
Replace with:
```csharp
return Profiles [name] = CreateProfile (name); 
```

2019-08-03 07:27 UTC, Therzok commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/LaunchProfileProvider.cs
> +			Profiles = new ConcurrentDictionary<string, LaunchProfileData> (profiles);
Remove the redundant intermediate dictionary, and set the value directly:
```csharp
			Profiles = new ConcurrentDictionary<string, LaunchProfileData>();
			Profiles.TryAdd (defaultNamespace, CreateDefaultProfile ());
```

2019-08-03 07:29 UTC, Therzok commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/LaunchProfileProvider.cs
> +					var index = project.RunConfigurations.IndexOf (runConfig);
Validate the return value is `>= 0` or Debug.Assert it if we expect it to always be found:
```csharp
if (index >= 0) ... // do stuff

// or

Debug.Assert (index >= 0, "Expected value to be found");
```

2019-08-03 07:30 UTC, Therzok commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/LaunchProfileProvider.cs
> +					var index = project.RunConfigurations.IndexOf (runConfig);
I expect it's the latter. Maybe it would be worth refactoring so we get the index of the first run configuration matching the `Name`, and do the `>= 0` check there. I'm wary of race conditions.

2019-08-03 07:30 UTC, Therzok commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/LaunchProfileProvider.cs
> +				if (Profiles.TryGetValue (key, out var _))
```suggestion
				if (Profiles.TryGetValue (key, out _))
```

2019-08-03 07:31 UTC, Therzok commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
> +			aspNetCoreRunConfs.Add (name, aspnetconf);
Threading concerns? If the value was added already by another thread, we can race here.

2019-08-03 07:31 UTC, Therzok commented on main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
> +			aspNetCoreRunConfs.Add (name, aspnetconf);
If we expect this to be called from the main thread only, add a `Runtime.AssertMainThread()` at the top of the method.

2019-08-03 07:33 UTC, Therzok commented
First review pass, mostly LGTM!

2019-08-15 09:15 UTC, rodrmoya commented
@monojenkins backport pr-8.3-launch-settings-fix

2019-08-15 09:16 UTC, merged