Master collection pool
mono/monodevelop pull request #7995
Opened 2019-06-24 08:23 UTC by mkrueger

2019-06-24 12:04 UTC, Therzok commented
We have object pooling via Microsoft.Extensions.ObjectPool

2019-06-24 15:47 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/CollectionCache.cs
> +		public static List<T> AllocateList<T> () => Pool<T, List<T>>.Allocate ();
I'm not sure we want a global collection cache. This would keep some objects in memory regardless of the component being used or not.

We could provide a global collection policy that would clear and check for capacity. But I wouldn't make static pools for a generic `List<T>`.

2019-06-24 15:49 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/CollectionCache.cs
> +			class PooledObjectPolicy : PooledObjectPolicy<U>
In example, I'd make just this public API and that's it. Every code path should have a local pool they're responsible for, either per service or per instance. A global pool for a type used only on solution load would just 'leak' objects for a long time.

2019-06-24 15:51 UTC, Therzok requested changes
We need to have a better placement for collection pooling, usually scoped to the pool user, not as a service.

2019-06-25 06:16 UTC, mkrueger commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/CollectionCache.cs
> +			class PooledObjectPolicy : PooledObjectPolicy<U>
Wouldn't leak - it would be constant which is a big difference. 

Other than that - yes it's not useful for every case but there are often useful.

2019-06-25 06:18 UTC, mkrueger commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/CollectionCache.cs
> +		public static List<T> AllocateList<T> () => Pool<T, List<T>>.Allocate ();
Hard to tell that's why I want to discuss it. I'm sure you see in the profiler as well that we've high memory traffic of arrays beeing created. 

Re-using collections is something we can try to lower the memory traffic. I agree that it's not useful for every case but we need to find the hot spots for memory traffic and reduce them.

ATM I don't have a profiler for that :/. In the old editor there would've been several places where collection pooling would be useful.

2019-06-25 09:32 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/CollectionCache.cs
> +		public static List<T> AllocateList<T> () => Pool<T, List<T>>.Allocate ();
Yes, but what I mean is make the services in the assemblies that need to hold it alive, not in Core. Having too many users of a pool means that we can potentially have more than 1000 pooled objects kept alive simply because too many requested them, and returning them will add them onto the pool.

In example, say a pool has a default of 16 members, if we end up having too many concurrent users, we can possibly request 1000. That means 1000 allocations that will remain in memory _forever_. It's not a constant.

2019-06-25 09:32 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/CollectionCache.cs
> +			class PooledObjectPolicy : PooledObjectPolicy<U>
Using ObjectPool in the text editor would be better than having this in Core.

2019-06-26 06:40 UTC, mkrueger commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/CollectionCache.cs
> +		public static List<T> AllocateList<T> () => Pool<T, List<T>>.Allocate ();
It's a constant it'll always have an upper limit.

2019-06-26 06:55 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/CollectionCache.cs
> +		public static List<T> AllocateList<T> () => Pool<T, List<T>>.Allocate ();
What I meant is we can possibly have 16 collections with 1000 members each. So that's 16000 objects that will indefinitely remain in memory. The internal arrays for List<T> count. I'm still not sold on having APIs for open-ended collections `List<T>`. Local pools for _specific types_ is what we need.

Since we have addin unloading, for example, if an addin for a given T is unloaded, this will crash.

2019-06-26 09:36 UTC, rodrmoya commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/CollectionCache.cs
> +		public static List<T> AllocateList<T> () => Pool<T, List<T>>.Allocate ();
Maybe retained collections could have an expiration time? Not sure though if that would make the code better or worse, as, I guess, this means storing creation date per collection, iterate over all collections regularly, etc

2019-06-26 09:43 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/CollectionCache.cs
> +		public static List<T> AllocateList<T> () => Pool<T, List<T>>.Allocate ();
Expiration time does not solve the crash I mentioend above.****

2019-06-26 09:44 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/CollectionCache.cs
> +		public static List<T> AllocateList<T> () => Pool<T, List<T>>.Allocate ();
Again, how much more code is just doing:
```
new ObjectPool<List<T>> (MonoDevelop.Core.CollectionPoolPolicy ();
```

2019-06-26 23:10 UTC, Therzok commented
I'm okay with the objectpool usage, just not exposing this kind of API.

2019-06-26 23:13 UTC, Therzok commented
@mkrueger how would having something like, sound to you? That way we keep the pool _outside_ MD.Core, and we just provide utility helpers.

```
static class CollectionPoolHelpers
{
    public ObjectPool<List<T>> CreateListPool<T> ();
    public ObjectPool<HashSet<T>> CreateHashSetPool<T> ();
}
```

2019-06-28 05:24 UTC, mkrueger commented
CollectionPoolHelpers sounds ok that would work. I'll implement that - but using more pooling is something we should do at many parts.

2019-07-17 10:56 UTC, Therzok approved these changes
Much better!

2019-08-02 15:44 UTC, sevoku approved these changes
LGTM! Can we fix the build and merge this?

2019-08-03 04:07 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/ObjectPoolUtil.cs
> +		class PooledStackPolicy<T> : PooledObjectPolicy<Stack<T>>
```suggestion
		sealed class PooledStackPolicy<T> : PooledObjectPolicy<Stack<T>>
```

2019-08-03 04:07 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/ObjectPoolUtil.cs
> +		class PooledQueuePolicy<T> : PooledObjectPolicy<Queue<T>>
```suggestion
		sealed class PooledQueuePolicy<T> : PooledObjectPolicy<Queue<T>>
```

2019-08-03 04:09 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/ObjectPoolUtil.cs
> +			public override U Create () => new U ();
This might bite us. It uses reflection (Activator.CreateInstance). We can probably have a pooled HashSet policy.

2019-08-15 05:09 UTC, mkrueger commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/ObjectPoolUtil.cs
> +			public override U Create () => new U ();
wtf - .NET what have you done ?!?!?!

The question is: Can the JIT optimize that ?

2019-08-15 16:08 UTC, Therzok approved these changes

2019-08-21 01:18 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/SegmentTree.cs
> +using MonoDevelop.Core;
```suggestion
using MonoDevelop.Core;
using Microsoft.Extensions.ObjectPool;
```

2019-08-21 01:18 UTC, Therzok commented
Added a commit to fix the build

2019-09-05 04:47 UTC, Therzok commented
@sevoku can you take alook at merge this?

2019-09-26 06:31 UTC, Therzok approved these changes

2019-10-21 16:16 UTC, Therzok commented
@monojenkins rebase

2019-10-29 06:28 UTC, merged