Adds a ZOrder system based in GtkNSViewHost
mono/monodevelop pull request #8032
Opened 2019-06-26 17:11 UTC by netonjm

2019-06-26 20:28 UTC, Therzok approved these changes

2019-06-26 20:28 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +			if (superview.Subviews.Length == 0) {
Cache this in a local variable

2019-06-26 20:28 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +			int i = superview.Subviews.Length - 1;
superview.Subviews creates a new array every time. Cache it in a local variable then use it

2019-06-26 20:28 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +			var zOrderedViews = superview.Subviews.OfType<IGdkZOrderHostView> ();
Same problem here.

2019-06-26 20:28 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +				zOrderView = zOrderedViews.ElementAt (i);
Why LINQ here.

2019-06-26 20:29 UTC, Therzok requested changes
Meant to request changes.

2019-06-27 07:34 UTC, sevoku commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +			var zOrderedViews = superview.Subviews.OfType<IGdkZOrderHostView> ();
I wouldn't use Linq here at all, just foreach the subviews

2019-06-27 07:42 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +			if (superview.Subviews.Length == 0) {
Fixed

2019-06-27 07:42 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +			int i = superview.Subviews.Length - 1;
Fixed

2019-06-27 07:42 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +			var zOrderedViews = superview.Subviews.OfType<IGdkZOrderHostView> ();
Fixed

2019-06-27 07:42 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +				zOrderView = zOrderedViews.ElementAt (i);
Fixed

2019-06-27 07:44 UTC, sevoku reviewed
Shouldn't we revert https://github.com/mono/monodevelop/commit/c142766f069aef16c00793929ecc6f00d2efa5e0? Shouldn't be required if we insert correctly initially, right?
EDIT: per offline discussion: no, it's still useful and won't interfere with the new logic

2019-06-27 07:44 UTC, sevoku commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +			var zOrderedViews = subviews.ToListOfType<IGdkZOrderHostView> ();
Why this? can't we just use a foreach below and continue if the item does not implement the iface?

2019-06-27 08:15 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +			var zOrderedViews = subviews.ToListOfType<IGdkZOrderHostView> ();
Fixed!

2019-06-27 12:21 UTC, sevoku approved these changes
Tested the build and it works much better now!

2019-06-27 12:22 UTC, sevoku commented
@monojenkins backport release-8.2
@monojenkins backport release-8.1

2019-06-27 13:58 UTC, monojenkins commented
@sevoku backporting to release-8.1 failed, the patch results in conflicts:

```
Applying: Adds the splitter size like a constant
Applying: Adds a ZOrder layer based in GtkNSViewHost
Using index info to reconstruct a base tree...
M	main/src/core/MonoDevelop.Ide/MonoDevelop.Components/HPanedThin.cs
A	main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/DragEventTrapView.cs
Falling back to patching base and 3-way merge...
Auto-merging main/src/core/MonoDevelop.Ide/MonoDevelop.Components/HPanedThin.cs
CONFLICT (content): Merge conflict in main/src/core/MonoDevelop.Ide/MonoDevelop.Components/HPanedThin.cs
Auto-merging main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/MacSplitterWidget.cs
CONFLICT (content): Merge conflict in main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/MacSplitterWidget.cs
error: Failed to merge in the changes.
Patch failed at 0002 Adds a ZOrder layer based in GtkNSViewHost
```

Please backport manually!

2019-06-27 16:49 UTC, slluis commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockContainer.cs
>  				a.X -= 2;
This should be `(int)(SplitterSize / 2)`

2019-06-27 16:51 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockContainer.cs
>  				a.X -= 2;
good catch !

2019-06-27 17:05 UTC, abock requested changes

2019-06-27 17:05 UTC, abock commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +		static NSView GetParentNormalViewForInserting (NSView[] subviews)
I think the logic of subview additions/ordering via the `IGdkZOrderHostView` hints should be handled via [sortSubviewsUsingFunction:context:](https://developer.apple.com/documentation/appkit/nsview/1483805-sortsubviewsusingfunction?language=objc).

2019-06-27 17:06 UTC, abock commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +		static NSView GetParentNormalViewForInserting (NSView[] subviews)
Further, this can be done "automatically" by overriding `didAddSubview:` and calling the sort function.

2019-06-27 17:10 UTC, abock commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +	public interface IGdkZOrderHostView
Can we pick a better name for this? It really has nothing to do with GDK.

```csharp
interface INSViewOrdering
{
    int ZOrder { get; }
}
```

2019-06-27 17:11 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +	public interface IGdkZOrderHostView
sounds great to me 👍

2019-06-27 17:15 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +		static NSView GetParentNormalViewForInserting (NSView[] subviews)
Makes sense! good point @abock !

2019-06-28 02:44 UTC, Therzok reviewed
LGTM, even better after @abock 's comments are addressed.

2019-06-28 15:30 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockContainer.cs
>  				a.X -= 2;
Fixed

2019-06-28 15:30 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +	public interface IGdkZOrderHostView
Fixed

2019-07-03 10:24 UTC, netonjm commented
@abock DONE! 🎉🎉🎉

2019-07-03 10:26 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +		static NSView GetParentNormalViewForInserting (NSView[] subviews)
Done!

2019-07-03 11:39 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/NSViewExtensions.cs
> +		class SortData
```suggestion
		sealed class SortData
```

2019-07-03 12:00 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/NSViewExtensions.cs
> +			MonoDevelop.Components.Mac.Messaging.void_objc_msgSend_IntPtr_IntPtr (view.Handle, Selector.GetHandle ("sortSubviewsUsingFunction:context:"), function_pointer, context);
Cache the selector handle, the lookup is expensive.

2019-07-03 13:52 UTC, abock requested changes
Looking good! Just a few more minor things.

2019-07-03 13:52 UTC, abock commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +		public int GdkZOrder { get; }
Drop the Gdk prefix.

```csharp
public int ZOrder { get; }
```

2019-07-03 13:52 UTC, abock commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +				if (view2 is INSViewOrdering viewOrdering2) {
```csharp
if (view2 is INSViewOrdering viewOrdering2 &&
    viewOrdering2.GdkZOrder >= viewOrdering1.GdkZOrder)
    return NSComparisonResult.Ascending;
```

2019-07-03 13:52 UTC, abock commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/NSViewExtensions.cs
> +// Copyright (c) 2019
```csharp
// Copyright (c) Microsoft Corp. (https://www.microsoft.com)
```

And drop the Author section of the header.

2019-07-03 13:52 UTC, abock commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/NSViewExtensions.cs
> +			MonoDevelop.Components.Mac.Messaging.void_objc_msgSend_IntPtr_IntPtr (view.Handle, Selector.GetHandle ("sortSubviewsUsingFunction:context:"), function_pointer, context);
```csharp
static readonly Selector sel_sortSubviewsUsingFunction_context_
    = Selector.GetHandle ("sortSubviewsUsingFunction:context:");
```

2019-07-03 13:52 UTC, abock commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +					superview.AddSubview (view);
File a work item against the shell area path and assign to me to add a shared backing `NSView` for the host so we can resort subviews on subsequent add/removes?

2019-07-03 13:52 UTC, abock commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +using System.Linq;
I think you might be able to drop these `using`s now?

2019-07-03 16:35 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +				if (view2 is INSViewOrdering viewOrdering2) {
Done!

2019-07-03 16:35 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/NSViewExtensions.cs
> +// Copyright (c) 2019
Done

2019-07-03 16:35 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/NSViewExtensions.cs
> +		class SortData
Done

2019-07-03 16:36 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +		public int GdkZOrder { get; }
Fixed

2019-07-03 16:46 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +using System.Linq;
Fixed

2019-07-03 16:48 UTC, sevoku commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/NSViewExtensions.cs
> +// Copyright (c) 2019
Why this?

2019-07-03 17:17 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/NSViewExtensions.cs
> +			MonoDevelop.Components.Mac.Messaging.void_objc_msgSend_IntPtr_IntPtr (view.Handle, Selector.GetHandle ("sortSubviewsUsingFunction:context:"), function_pointer, context);
Fixed

2019-07-03 17:17 UTC, netonjm commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
> +					superview.AddSubview (view);
Fixed

2019-07-03 17:25 UTC, sevoku commented
@monojenkins backport release-8.2

2019-07-03 18:40 UTC, sevoku approved these changes

2019-07-03 18:43 UTC, sevoku commented
I've verified the backport build and it works great!

2019-07-03 20:21 UTC, abock approved these changes

2019-07-03 20:24 UTC, abock commented
Awesome. All of @Therzok's comments are addressed, so I'm merging this through.

2019-07-03 20:24 UTC, merged

2019-07-04 00:57 UTC, Therzok commented
Yep, LGTM!