Change Key binding scheme for Visual Studio for Mac
mono/monodevelop pull request #8071
Opened 2019-06-28 11:11 UTC by jsuarezruiz

We want to change key binding scheme for Visual Studio for Mac from "Visual Studio" to "Visual Studio for Mac". To do this (and since the previous branding properties did not fit) a new property (DefaultKeybindingSchemeName) has been created in the Branding.xml file.

Fixes VSTS #936531

2019-06-28 12:13 UTC, Therzok approved these changes

2019-07-01 13:05 UTC, sevoku approved these changes

2019-07-11 11:08 UTC, netonjm approved these changes

2019-07-17 12:44 UTC, sevoku requested changes

2019-07-17 12:44 UTC, sevoku commented on main/src/core/MonoDevelop.Ide/ExtensionModel/MonoDevelop.Ide.addin.xml
> +		<Scheme id="VS05" _name = "Visual Studio for Mac" resource="KeyBindingSchemeVisualStudio.xml"/>
This is the VS scheme visible on Windows/Linux only and not a Mac scheme.

2019-07-17 12:49 UTC, sevoku approved these changes

2019-07-17 12:49 UTC, netonjm approved these changes
LGTM!

2019-07-18 13:28 UTC, merged