Sourcelink
mono/monodevelop pull request #8239
Opened 2019-07-19 15:56 UTC by nosami

2019-07-19 15:59 UTC, nosami commented
depends on https://github.com/mono/debugger-libs/pull/235

2019-07-19 20:11 UTC, nosami commented
NetCoreBreakpointsAndSteppingTests tests failing

2019-07-22 11:11 UTC, slluis requested changes
Test scenarios and use cases need to be [documented](https://github.com/xamarin/md-addins/tree/master/test-scenarios).

2019-07-22 13:39 UTC, nosami commented
NetCoreBreakpointsAndSteppingTests tests fixed

2019-07-31 08:09 UTC, mrward approved these changes

2019-07-31 09:48 UTC, mrward commented
There are some problems with the UI thread hanging but this looks like a problem in the text editor.

2019-07-31 13:02 UTC, jstedfast approved these changes

2019-08-02 16:31 UTC, nosami commented
Editor UI hang has gone since rebasing on master

2019-08-03 04:38 UTC, Therzok commented on main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggerOptionsPanelWidget.cs
> +			options.ProjectAssembliesOnly = !checkProjectCodeOnly.Active;
Hmmm, why was this inverted?

2019-08-03 04:38 UTC, Therzok commented on main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggerOptionsPanelWidget.cs
> +			checkProjectCodeOnly.Active = !options.ProjectAssembliesOnly;
same here.

2019-08-03 04:38 UTC, Therzok commented on main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggerOptionsPanelWidget.cs
> +			checkProjectCodeOnly = new CheckBox (GettextCatalog.GetString ("Step into external code")) {
The name of the checkbox should change too. This would reflect why we inverted the values for users.

2019-08-03 04:42 UTC, Therzok commented on main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Initializer.cs
> +			symbolCachePath = UserProfile.Current.CacheDir.Combine ("Symbols");
I'm wondering if this should be user configurable. The VSMac cache folder could get pretty big, as we do no invalidation here based on size.

2019-08-03 04:48 UTC, Therzok commented on main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Initializer.cs
> +			symbolCachePath = UserProfile.Current.CacheDir.Combine ("Symbols");
I'm wondering whether we should dump the symbol server information in the `.vs` directory and maintain a mapping in the cache folder if we want to de-duplicate symbol server downloads?

2019-08-03 04:50 UTC, Therzok commented on main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Initializer.cs
> +								("{0} is a call to external source code. Would you like to get {1} and view it?", stackframeText, hyperlink);
```suggestion
								("{0} is a call to external source code. Would you like to get '{1}' and view it?", stackframeText, hyperlink);
```

2019-08-03 04:51 UTC, Therzok commented on main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Initializer.cs
> +				GettextCatalog.GetString ("Downloading ") + sourceLink.Uri,
```suggestion
				GettextCatalog.GetString ("Downloading {0}", sourceLink.Uri),
```

2019-08-03 04:51 UTC, Therzok commented on main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Initializer.cs
> +				Stock.StatusWorking,
```suggestion
				Stock.StatusDownload,
```

2019-08-03 05:09 UTC, Therzok commented on main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Initializer.cs
> +				Directory.GetParent (downloadLocation).Create ();
```suggestion
				Directory.CreateDirectory (Path.GetDirectoryName (downloadLocation));
```

Avoids a redundant DirectoryInfo allocation.

2019-08-03 05:11 UTC, Therzok commented on main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Initializer.cs
> +				using (var stream = await client.GetStreamAsync (sourceLink.Uri)) {
Do we need UpdateSourceFile to run on the UI thread? Otherwise, I think we can safely do:
```csharp
using (var stream = await client.GetStreamAsync (sourceLink.Uri).ConfigureAwait (false))
using (var fs = new FileStream (downloadLocation, FileMode.CreateNew)) {
	await stream.CopyToAsync (fs).ConfigureAwait (false);
}
frame.UpdateSourceFile (downloadLocation);
doc = await Runtime.RunInMainThread (() => IdeApp.Workbench.OpenDocument (downloadLocation, null, line, 1, OpenDocumentOptions.Debugger));
```

2019-08-03 05:13 UTC, Therzok commented on main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Initializer.cs
> +				using (var stream = await client.GetStreamAsync (sourceLink.Uri)) {
We should also pass `FileMode.Create`, as we could have a broken file hash if a download failure occurred, so we want to truncate and update the current file.

2019-08-03 05:13 UTC, Therzok commented on main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Initializer.cs
> +			} catch (Exception ex) {
We should also do something to notify the user if a download fails or there's no connectivity?

2019-08-03 05:14 UTC, Therzok commented on main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Initializer.cs
> +		async System.Threading.Tasks.Task<Document> DownloadAndOpenFileAsync (StackFrame frame, int line, SourceLink sourceLink)
$0.02 nitpick: This method should probably receive a monitor and pass the filepath, so we can have it free-threaded on a background thread.

Then, the caller would call `OpenDocument` and handle being on the UI thread.

2019-08-03 05:15 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DocumentRegistry.cs
> +				view.LastSaveTimeUtc = File.GetLastWriteTimeUtc (view.Document.FileName);
Nice catch!

2019-08-03 05:16 UTC, Therzok reviewed
Done with first review pass

2019-08-03 05:44 UTC, Therzok commented
Done with review pass 1.

2019-08-04 21:51 UTC, nosami commented on main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Initializer.cs
> +			symbolCachePath = UserProfile.Current.CacheDir.Combine ("Symbols");
> I'm wondering if this should be user configurable. The VSMac cache folder could get pretty big, as we do no invalidation here based on size.

On VS Windows, the cache path is configurable. I think @hbons was wanting to minimize the amount of configuration required here.

> I'm wondering whether we should dump the symbol server information in the .vs directory and have no problems with a global cache?

Sharing symbols seems like a good idea to me - less to download when symbols are shared between solutions (probably common for things like runtime code or Newtonsoft :) )

2019-08-04 21:54 UTC, nosami commented on main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggerOptionsPanelWidget.cs
> +			checkProjectCodeOnly = new CheckBox (GettextCatalog.GetString ("Step into external code")) {
I think I meant to do this but forgot :)

2019-08-04 22:02 UTC, nosami commented on main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Initializer.cs
> +				using (var stream = await client.GetStreamAsync (sourceLink.Uri)) {
UpdateSourceFile can run on any thread, I'll apply your suggestion

2019-08-05 04:53 UTC, Therzok commented on main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Initializer.cs
> +				bool alternateLocationExists = false;
We don't need this boolean, imo. From the BCL docs:

Create | 2 | Specifies that the operating system should create a new file. If the file already exists, it will be overwritten. This requires Write permission. FileMode.Create is equivalent to requesting that if the file does not exist, use CreateNew; otherwise, use Truncate. If the file already exists but is a hidden file, an UnauthorizedAccessException exception is thrown.

2019-08-07 11:10 UTC, Therzok commented
Took it for a spin, it works for me.

Minor nits, which I leave to the design folks to look at:
<img width="453" alt="Screenshot 2019-08-07 at 14 05 42" src="https://user-images.githubusercontent.com/109974/62618420-d7aa5d00-b91c-11e9-839a-ce008a548370.png">

I think we should disable interaction with the combobox when the external code check is untoggled.

2019-08-07 11:10 UTC, Therzok commented
cc @vancura @hbons

2019-08-07 12:24 UTC, nosami commented
> I think we should disable interaction with the combobox when the external code check is untoggled.

Done

![togglecombo](https://user-images.githubusercontent.com/667194/62622575-931bc300-b916-11e9-956f-66c177c3c05b.gif)

2019-08-07 12:34 UTC, Therzok approved these changes

2019-08-07 12:35 UTC, Therzok requested changes
Revert the git -> https change in gitmodules and revert the vs-editor bump.

2019-08-07 12:35 UTC, Therzok commented on .gitmodules
> +	url = https://github.com/mono/debugger-libs.git
Revert this change

2019-08-07 12:41 UTC, nosami commented on .gitmodules
> +	url = https://github.com/mono/debugger-libs.git
done

2019-08-07 12:48 UTC, Therzok approved these changes

2019-08-07 17:39 UTC, sgmunn commented
as I understand it, the .net core tests are failing with a mono bug

2019-08-07 17:45 UTC, merged