[VersionControl] Directory removal is now checked.
mono/monodevelop pull request #8368
Opened 2019-08-09 09:18 UTC by mkrueger

2019-08-09 11:35 UTC, sevoku commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
> +			if (lockedDirectories.Contains (path.FullPath)) {
Shouldn't we use `path.FullPath.CanoncialPath` here? Not sure if `FullPath` might contain a separator at the end...

2019-08-09 11:35 UTC, sevoku commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
> +				lockedDirectories.Add (path);
Use CanonicalPath here?

2019-08-09 11:45 UTC, mkrueger commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
> +			if (lockedDirectories.Contains (path.FullPath)) {
added.

2019-08-09 11:48 UTC, mkrueger commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
> +				lockedDirectories.Add (path);
added.

2019-08-09 11:50 UTC, mkrueger commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
> +			lockedDirectories.Add ("/");
added.

I thought we're not supporting Windows anymore ?

2019-08-09 11:50 UTC, sevoku commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
> +				throw new InvalidOperationException ("Can't delete directory " + path + ".");
It might be worth catching any exception when we delete a folder after a failed VCS operation.

2019-08-09 11:50 UTC, mkrueger commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
> +				throw new InvalidOperationException ("Can't delete directory " + path + ".");
Doesn't matter much, better IDE crash than removing the user folder. 

In general Exception is cached by running operations.

2019-08-09 11:53 UTC, sevoku commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
> +			lockedDirectories.Add ("/");
Or:
```cs
if (Platform.IsWindows)
     lockedDirectories.Add ("c:/");
else
     lockedDirectories.Add ("/");
```

2019-08-09 12:16 UTC, mkrueger commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
> +				lockedDirectories.Add ("/");
+1.

2019-08-09 12:17 UTC, mkrueger commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
> +				FilePath parent = requiredParentDirectory;
+1 searched for that one.

2019-08-09 12:27 UTC, sevoku approved these changes

2019-08-09 12:28 UTC, sevoku commented
@monojenkins backport release-8.2
@monojenkins backport release-8.3

2019-08-09 13:55 UTC, Therzok commented
@mkrueger can you add a unit test asserting we can't remove `/`?

2019-08-09 13:56 UTC, Therzok commented
/me is wary of how things will go wrong, but oh well

2019-08-09 13:57 UTC, Therzok requested changes

2019-08-09 13:57 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
> +		public static void AssertCanDeleteDirectory (FilePath path, string requiredParentDirectory = null)
Needs unit tests

2019-08-09 13:57 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FilePath.cs
> +			if (startsWith && (basePath.fileName [basePath.fileName.Length - 1] != Path.DirectorySeparatorChar ||
Needs unit tests. What is the change here?

2019-08-09 14:09 UTC, Therzok commented
Also, git failure:
```
2019-08-09T13:23:48.2824830Z 1) BaseRepoUtilsTest.DeletesDirectory (MonoDevelop.VersionControl.Git.Tests.BaseGitUtilsTest.BaseRepoUtilsTest.DeletesDirectory)
2019-08-09T13:23:48.2826930Z Expected: ScheduledDelete
2019-08-09T13:23:48.2827390Z But was: Unversioned
2019-08-09T13:23:48.2827500Z
2019-08-09T13:23:48.2827920Z at MonoDevelop.VersionControl.Tests.BaseRepoUtilsTest.DeleteTestDirectoryHelper (System.Boolean keepLocal) [0x00222] in /Users/vsts/agent/2.155.1/work/1/s/monodevelop/main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/BaseRepositoryTests.cs:508
2019-08-09T13:23:48.2828310Z at MonoDevelop.VersionControl.Tests.BaseRepoUtilsTest.DeletesDirectory () [0x00025] in /Users/vsts/agent/2.155.1/work/1/s/monodevelop/main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/BaseRepositoryTests.cs:538
```

2019-08-09 16:21 UTC, sevoku requested changes

2019-08-09 17:41 UTC, sevoku commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
> +		public static void AssertCanDeleteDirectory (FilePath path, string requiredParentDirectory = null, bool canDeleteParent = true)
Pls add the new param to the xml comment and maybe use a better name? `canDeleteParent` is confusing, what am I checking? Parent or path?
```suggestion
		public static void AssertCanDeleteDirectory (FilePath path, string requiredParentDirectory = null, bool includingParent = true)
```

2019-08-09 17:42 UTC, sevoku commented on main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/FileServiceTests.cs
> +			FileService.AssertCanDeleteDirectory (Environment.GetFolderPath (Environment.SpecialFolder.ApplicationData));
also `Environment.SpecialFolder.MyDocuments` and `Environment.SpecialFolder.UserProfile`, just in case. I know it doesn't matter with current impl, but anyway. We don't want to delete these important folders, so let's test that.

2019-08-09 18:03 UTC, mkrueger commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
> +		public static void AssertCanDeleteDirectory (FilePath path, string requiredParentDirectory = null)
added

2019-08-09 18:03 UTC, mkrueger commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FilePath.cs
> +			if (startsWith && (basePath.fileName [basePath.fileName.Length - 1] != Path.DirectorySeparatorChar ||
tests added.

2019-08-09 18:08 UTC, mkrueger commented on main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/FileServiceTests.cs
> +			FileService.AssertCanDeleteDirectory (Environment.GetFolderPath (Environment.SpecialFolder.ApplicationData));
ok but I don't think they're needed.

2019-08-09 18:08 UTC, mkrueger commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
> +		public static void AssertCanDeleteDirectory (FilePath path, string requiredParentDirectory = null, bool canDeleteParent = true)
added docs. I don't think the old name is confusing because it basically says what it is for.

2019-08-10 08:04 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core/FilePath.cs
> +			if (startsWith && (basePath.fileName [basePath.fileName.Length - 1] != Path.DirectorySeparatorChar ||
@sevoku only applicable on windows, as the other slash is a valid character in a path, not a separator.

2019-08-10 08:05 UTC, Therzok commented on main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/FileServiceTests.cs
> +			FileService.AssertCanDeleteDirectory (Directory.GetLogicalDrives () [0]);
Iterate through all of them

2019-08-12 07:54 UTC, mkrueger commented on main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/FileServiceTests.cs
> +			FileService.AssertCanDeleteDirectory (Directory.GetLogicalDrives () [0]);
Not needed for unit tests. That would basically test the implementation using implementation source code.

2019-08-12 08:23 UTC, Therzok commented on main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/FileServiceTests.cs
> +			FileService.AssertCanDeleteDirectory (Directory.GetLogicalDrives () [0]);
By that argument, we should be testing `/` on Unix and `C:` on Windows, not GetLogicalDrives.

2019-08-13 06:06 UTC, mkrueger commented on main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/FileServiceTests.cs
> +			FileService.AssertCanDeleteDirectory (Directory.GetLogicalDrives () [0]);
That's true - fixed that'll make it more visible what's intended.

2019-08-13 08:26 UTC, sevoku approved these changes

2019-08-13 13:56 UTC, Therzok approved these changes

2019-08-14 04:19 UTC, merged

2019-08-14 04:20 UTC, mkrueger commented
@monojenkins backport release-8.2
@monojenkins backport release-8.3

2019-08-14 04:20 UTC, monojenkins commented
@mkrueger backporting to release-8.2 failed, the patch results in conflicts:

```
Applying: [VersionControl] Directory removal is now checked.
Using index info to reconstruct a base tree...
M	main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
M	main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion/MonoDevelop.VersionControl.Subversion/SubversionRepository.cs
M	main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
M	main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
.git/rebase-apply/patch:123: trailing whitespace.
		
warning: 1 line adds whitespace errors.
Falling back to patching base and 3-way merge...
Auto-merging main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
Auto-merging main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
Auto-merging main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion/MonoDevelop.VersionControl.Subversion/SubversionRepository.cs
CONFLICT (content): Merge conflict in main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion/MonoDevelop.VersionControl.Subversion/SubversionRepository.cs
Auto-merging main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
error: Failed to merge in the changes.
Patch failed at 0001 [VersionControl] Directory removal is now checked.
```

Please backport manually!

2019-08-15 06:57 UTC, sevoku commented
@monojenkins backport release-8.2

2019-08-15 06:58 UTC, monojenkins commented
@sevoku backporting to release-8.2 failed, the patch results in conflicts:

```
Applying: [VersionControl] Directory removal is now checked.
Using index info to reconstruct a base tree...
M	main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
M	main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion/MonoDevelop.VersionControl.Subversion/SubversionRepository.cs
M	main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
M	main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
.git/rebase-apply/patch:123: trailing whitespace.
		
warning: 1 line adds whitespace errors.
Falling back to patching base and 3-way merge...
Auto-merging main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
Auto-merging main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
Auto-merging main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion/MonoDevelop.VersionControl.Subversion/SubversionRepository.cs
CONFLICT (content): Merge conflict in main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion/MonoDevelop.VersionControl.Subversion/SubversionRepository.cs
Auto-merging main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
error: Failed to merge in the changes.
Patch failed at 0001 [VersionControl] Directory removal is now checked.
```

Please backport manually!

2019-08-15 07:00 UTC, sevoku commented
@monojenkins backport release-8.3
to get a green build