Master vsts961650
mono/monodevelop pull request #8405
Opened 2019-08-13 13:20 UTC by mkrueger

2019-08-15 16:17 UTC, sevoku requested changes
@mkrueger this needs a rebase

2019-08-16 09:22 UTC, sevoku approved these changes
@monojenkins backport release-8.3

2019-08-16 09:27 UTC, sevoku commented
@monojenkins backport release-8.3

2019-08-16 10:11 UTC, Therzok approved these changes

2019-08-16 10:37 UTC, merged