Fix hang in file watcher
mono/monodevelop pull request #8688
Opened 2019-09-11 14:56 UTC by slluis

Enabling events has a sync wait on a flush of the IO event queue, and
that may take many seconds to complete if there is a lot of IO. To
avoid locking on this call, we now enable the events on a background
thread.

Fixes VSTS #952405 - Visual Studio Mac 2019 Freezes on Switch Branch
Fixes VSTS #980470 - Deadlock in FileWatcherService.WatchDirectories

2019-09-11 14:56 UTC, slluis commented
@monojenkins backport release-8.3

2019-09-11 15:00 UTC, slluis commented
@monojenkins backport release-8.3

2019-09-11 15:03 UTC, Therzok approved these changes

2019-09-11 15:14 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs
> +						Task.Run (EnableEvents).Ignore ();
Maybe we return this task so the service can return the task that actually waits for the watcher to be enabled.

2019-09-11 15:15 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs
> +						Task.Run (EnableEvents).Ignore ();
UpdateWatchers would then return a Task and UpdateWatchersAsync would return the Task.WhenAll for all of these.

2019-09-11 15:16 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs
> +						Task.Run (EnableEvents).Ignore ();
Otherwise we might see transient failures in VSTS because the directories aren't watched because of high IO.

2019-09-11 15:20 UTC, mrward commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs
> +						Task.Run (EnableEvents).Ignore ();
Yeah. I wonder if this will affect some tests. Some tests assume the watcher is created when file watcher service methods return which might not happen now. Have to see.

https://github.com/mono/monodevelop/blob/dea5016c423bcc2f827a557d33c32cc2e5e75e22/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs#L309

2019-09-11 15:20 UTC, mrward approved these changes

2019-09-11 15:32 UTC, Therzok requested changes
Marking as requesting changes. We need to handle the watcher being enabled by handling the task.

2019-09-11 19:16 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs
> +			return Task.Run (async () => await UpdateWatchers (token));
```suggestion
			return Task.Run (() => UpdateWatchers (token)).Unwrap ();
```

2019-09-11 19:19 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs
> +					}, TaskScheduler.Default);
```suggestion
					}, CancellationToken.None, TaskContinuationOptions.OnlyOnFaulted, TaskScheduler.Default);
```

2019-09-11 19:19 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs
> +						if (t.IsFaulted && t.Exception.InnerException is UnauthorizedAccessException e) {
Not needed anymore with TaskContinuationOptions.

2019-09-11 19:23 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs
> +		public void DisableRisingEvents ()
```suggestion
		public void DisableRaisingEvents ()
```

and other places.

2019-09-11 19:29 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs
> +		void EnableEvents (Task t)
t isn't used

2019-09-11 19:39 UTC, Therzok approved these changes
Looks good!

2019-09-11 19:41 UTC, slluis commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs
> +		void EnableEvents (Task t)
it is necessary to avoid a lambda in ContinueWith

2019-09-11 19:43 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs
> +		void EnableEvents (Task t)
I'll be pedantic a bit, but roslyn codegen sucks.

This reuses a cached `Action<Task>`
```csharp
ContinueWith (t => EnableEvents (t))
```

This always allocates an `Action<Task>`.
```csharp
ContinueWith (EnableEvents);
```

2019-09-11 19:44 UTC, slluis commented
@monojenkins backport release-8.3

2019-09-11 19:45 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs
> +		void EnableEvents (Task t)
Ah, nevermind! This is not a lambda without captures.

2019-09-11 21:50 UTC, slluis commented
@monojenkins backport release-8.3

2019-09-12 00:11 UTC, slluis commented
@monojenkins backport release-8.3

2019-09-12 00:29 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs
> +						tasks.Add (existingWatcher.EnableRaisingEventsAsync ());
:+1:

2019-09-12 07:11 UTC, merged