Improve feature switch service
mono/monodevelop pull request #9105
Opened 2019-10-26 14:18 UTC by rodrmoya

2019-10-26 14:58 UTC, nosami commented on main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreFeatureSwitchController.cs
> +	public class DotNetCoreFeatureSwitchController : IFeatureSwitchController
This should be named VBNetDotCoreFeatureSwitchController?

2019-10-26 18:04 UTC, rodrmoya commented on main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreFeatureSwitchController.cs
> +	public class DotNetCoreFeatureSwitchController : IFeatureSwitchController
Not really, the idea is to put there all .NET Core related feature toggles, it happens to have only VB.NET for now, but it will have more for sure (Blazor, for instance)

2019-10-27 07:28 UTC, Therzok requested changes
The assembly load issue should be fixed first, then I'll do another review pass.

2019-10-27 07:28 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +			AddinManager.AddExtensionNodeHandler (typeof (IFeatureSwitchController), HandleFeatureSwitchExtension);
This is going to force load a lot of assemblies on startup. What can we do (at addin.xml) to avoid this?

We need to register some kind of filters, because as the code is now, every assembly that defines an IFeatureSwitchController will be forcefully loaded when this constructor is hit.

2019-10-27 07:28 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +			AddinManager.AddExtensionNodeHandler (typeof (IFeatureSwitchController), HandleFeatureSwitchExtension);
Instead of registering a class, maybe we could express everything in xml metadata items (`id`, `_description`, `defaultValue`).

2019-10-27 11:18 UTC, mrward commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +		internal static IEnumerable<FeatureSwitch> DescribeFeatures ()
Are we going to have a way to enable/disable features in the IDE? Just wondering we have a description if nothing is using it and there is no way using the FeatureSwitchService to get all the features provided, without using `AddinManager.GetExtensionObjects<IFeatureSwitchController>` and checking each controller.

Reason I ask is that I was looking at a [feature switch addin](https://github.com/mrward/monodevelop-feature-switch-addin) that allowed you to enable/disable features but there was no way to discover all the features apart from when one was requested.

2019-10-27 11:35 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +		internal static IEnumerable<FeatureSwitch> DescribeFeatures ()
I like the approach in the feature switch addin!

2019-10-27 22:31 UTC, rodrmoya commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +			AddinManager.AddExtensionNodeHandler (typeof (IFeatureSwitchController), HandleFeatureSwitchExtension);
Yes, or maybe lazy loading?

2019-10-27 22:37 UTC, rodrmoya commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +		internal static IEnumerable<FeatureSwitch> DescribeFeatures ()
> Are we going to have a way to enable/disable features in the IDE? Just wondering we have a description if nothing is using it and there is no way using the FeatureSwitchService to get all the features provided, without using `AddinManager.GetExtensionObjects<IFeatureSwitchController>` and checking each controller.
> 
> Reason I ask is that I was looking at a [feature switch addin](https://github.com/mrward/monodevelop-feature-switch-addin) that allowed you to enable/disable features but there was no way to discover all the features apart from when one was requested.

yeah, was thinking about adding a UI for that, that's why I changed the implementation, but wasn't sure how to better add it, but your addin sounds a much better idea indeed! And indeed, the `DescribeFeatures` is exactly for that, I made it internal for now as nothing was using, apart from tests, but indeed, we can make it public, and even add a much better API to be used by that addin (like maybe events for when new features are added/removed/enabled, ...?)

2019-10-28 10:15 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +			AddinManager.AddExtensionNodeHandler (typeof (IFeatureSwitchController), HandleFeatureSwitchExtension);
Lazy loading can still trigger the assembly load problem if something uses feature switch service earlier in the IDE.

2019-11-02 01:39 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitch.cs
> +	public class FeatureSwitch
```suggestion
	internal class FeatureSwitch
```

2019-11-02 01:41 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +		static ImmutableDictionary<string, FeatureSwitch> featureSwitches = ImmutableDictionary<string, FeatureSwitch>.Empty;
Why ImmutableDictionary? Addin information is only processed on the UI thread, so there's no need for thread-safety.

2019-11-02 01:44 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +				if (args.Change == ExtensionChange.Add && !featureSwitches.TryGetValue (fs.Id, out _)) {
This is not quite correct. If the arg kind is `Add` and there already is a registered feature switch on that ID, it'll remove the existing one and not add the new one, making it so none are registered on the same ID.

Maybe log an error about it, and keep the first registered one.

2019-11-02 01:45 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +				if (args.Change == ExtensionChange.Add && !featureSwitches.TryGetValue (fs.Id, out _)) {
Maybe move the `TryGetValue` call inside `RegisterFeatureSwitch` so it's easier to reason about.

2019-11-02 01:47 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +
```suggestion

			Runtime.AssertMainThread ();
```

2019-11-02 01:48 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +			return featureSwitches?.Values;
```suggestion
			return featureSwitches.Values;
```

2019-11-02 01:48 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +			if (featureSwitches != null) {
this null check looks redundant.

2019-11-02 17:20 UTC, rodrmoya commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +			AddinManager.AddExtensionNodeHandler (typeof (IFeatureSwitchController), HandleFeatureSwitchExtension);
ok, moved now to be all in the addin.xml files, as indeed, all `IFeatureSwitchController` implementations were just returning the `defaultValue`

2019-11-02 17:28 UTC, rodrmoya commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitch.cs
> +	public class FeatureSwitch
I set it as public so that it could be used by @mrward 's addin, but I think there's no need for that, we can just have public API in `FeatureSwitchService`to do it, so changing to internal then

2019-11-02 17:29 UTC, rodrmoya commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +		static ImmutableDictionary<string, FeatureSwitch> featureSwitches = ImmutableDictionary<string, FeatureSwitch>.Empty;
Ah ok, just copied from other similar services, but better to use a simple `Dictionary`

2019-11-02 17:29 UTC, rodrmoya commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +				if (args.Change == ExtensionChange.Add && !featureSwitches.TryGetValue (fs.Id, out _)) {
yeah, changed now

2019-11-02 18:01 UTC, rodrmoya commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +		internal static IEnumerable<FeatureSwitch> DescribeFeatures ()
@mrward yeah, added -> https://github.com/mono/monodevelop/pull/9105/files#diff-9e619a97ca9961bdaeb48e7115c5cb91R90

2019-11-03 16:30 UTC, mrward commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitch.cs
> +	internal class FeatureSwitch
The problem here is that this is a public API break. This will break any addins that implement a feature switch controller, which is possibly is not going to be likely, but would break my addin, for example. IFeatureSwitchController has been available since v7.8.

2019-11-03 16:41 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitch.cs
> +	internal class FeatureSwitch
We can keep the old interface as back-compat, but obsolete it and remove it when possible. The old extensibility point causes force loads of assemblies due to having to instantiate the controllers at runtime.

2019-11-03 16:41 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.AddIns/FeatureSwitchExtensionNode.cs
> +	class FeatureSwitchExtensionNode : ExtensionNode
Serialization optimization:
```suggestion
	sealed class FeatureSwitchExtensionNode : ExtensionNode
```

2019-11-03 16:41 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitch.cs
> +	internal class FeatureSwitch
```suggestion
	internal sealed class FeatureSwitch
```

2019-11-03 22:07 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +
Add a main thread assertion, addinmanager can't be used from background threads.

2019-11-03 22:15 UTC, rodrmoya commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +
Yeah, well, this is called from `IsFeatureEnabled`, which should be possible to call from any thread, so just asserting will just throw an exception when so. Will look at improving the initialisation.

2019-11-03 22:27 UTC, rodrmoya commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitch.cs
> +	internal class FeatureSwitch
I've added back the interface and code to query `IFeatureSwitchController` implementations, although just as fall back if all the other methods "fail", so this will still break, although not API-related, Matt's addin, as his implementation will never be called for the feature flags that are correctly registered via the .addin.xml.

To fix that, I could move the fallback code to be run before checking the xml-based ones, but that would mean having the assembly load issue Marius was talking about, as soon as `IsFeatureEnabled` is called.

2019-11-04 10:33 UTC, Therzok requested changes

2019-11-04 10:33 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +			AddinManager.AddExtensionNodeHandler ("/MonoDevelop/Core/FeatureSwitches", HandleFeatureSwitchExtension);
We need to run this on the UI thread.

Please add a Runtime.AssertMainThread().

2019-11-04 11:54 UTC, mrward commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitch.cs
> +	internal class FeatureSwitch
Not that concerned about breaking my addin, I can update it. Supporting anybody else that has implemented IFeatureSwitchController properly is enough here.

2019-11-04 11:58 UTC, mrward approved these changes

2019-11-04 12:51 UTC, rodrmoya commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +			AddinManager.AddExtensionNodeHandler ("/MonoDevelop/Core/FeatureSwitches", HandleFeatureSwitchExtension);
But now that it is static, it should be run on the UI thread AFAICS from other similar implementations, do we still need it?

2019-11-04 12:52 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +			AddinManager.AddExtensionNodeHandler ("/MonoDevelop/Core/FeatureSwitches", HandleFeatureSwitchExtension);
This doesn't guarantee it's run on the UI thread. It's only run once, on the caller thread. Either add an `internal static Initialize()` and force call that on startup or add assert

2019-11-04 14:04 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +			AddinManager.AddExtensionNodeHandler ("/MonoDevelop/Core/FeatureSwitches", HandleFeatureSwitchExtension);
Or implement `IService`, http://source.monodevelop.com/#MonoDevelop.Core/MonoDevelop.Core/IService.cs,7a5d97d8a5b5df09,references

2019-11-04 14:06 UTC, Therzok commented on main/src/core/MonoDevelop.Core/MonoDevelop.Core.FeatureConfiguration/FeatureSwitchService.cs
> +			AddinManager.AddExtensionNodeHandler ("/MonoDevelop/Core/FeatureSwitches", HandleFeatureSwitchExtension);
Actually, might be simpler to extend `Service`:
http://source.monodevelop.com/#MonoDevelop.Core/MonoDevelop.Core/Service.cs,3f3b4ad9dcdc81c6,references

2019-11-09 23:17 UTC, Therzok approved these changes

2019-11-10 17:46 UTC, nosami approved these changes

2019-11-14 18:17 UTC, merged