Fixes VSTS Bug 1009809:
mono/monodevelop pull request #9230
Opened 2019-11-06 11:44 UTC by mkrueger

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1009809Save
failed

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1009809

2019-11-06 12:16 UTC, Therzok requested changes

2019-11-06 12:16 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
> +				monitor.Dispose ();
monitor.Dispose is redundant.

2019-11-06 15:10 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Window.cs
> +					; // nothing
We should at least log the exception.

2019-11-08 09:51 UTC, mkrueger commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Window.cs
> +					; // nothing
Not really it's kind of excepted and handled when nswindow == null.

2019-11-08 09:54 UTC, mkrueger commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
> +				monitor.Dispose ();
fixed.

2019-11-08 13:31 UTC, Therzok commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Window.cs
> +					nsWindow = parent.GetNativeWidget<NSWindow> ();
You need to check if the native widget is an via `parent.nativeWidget is NSWindow`. GetNativeWidget is expected to throw.

2019-11-11 07:25 UTC, mkrueger commented on main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Window.cs
> +					nsWindow = parent.GetNativeWidget<NSWindow> ();
That relies too much on the implementation details. I prefer doing it that way.

2019-11-12 08:27 UTC, sevoku approved these changes

2019-12-04 15:55 UTC, Therzok approved these changes

2019-12-05 13:37 UTC, sevoku commented
@monojenkins rebase

2019-12-06 00:02 UTC, bratsche approved these changes

2020-01-23 00:09 UTC, sevoku approved these changes

2020-01-23 00:10 UTC, merged